
# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        AgentImportEvalSuiteRequest,
        AgentImportImproveRequest,
        AgentImportModelCaptureRequest,
        AgentImportRunnerRequest,
        AgentImportSourceRefRequest,
        AgentImportSourceRefRequestExportPolicy,
        AnswerRef,
        CaseInput,
        CreateManagedAgentSourceRequest,
        CreateManagedAgentSourceRequestExportPolicy,
        CreateManagedAgentSourceRequestSourceKind,
        CreateParityRunRequest,
        EventDeliveryRequest,
        HttpValidationError,
        JudgmentContext,
        JudgmentTarget,
        JudgmentTargetKind,
        ManagedRun,
        OpenInferenceSpan,
        RecoverRunRequest,
        ReleaseActionRequest,
        ResumeImprovementInput,
        ResumeInput,
        RunEvent,
        RunEvents,
        ScopeType,
        SourceType,
        TargetInput,
        ToolProviderRefRequest,
        ToolSkillSourceRequest,
        TraceImportGroupingRequest,
        TraceImportOptionsRequest,
        TraceImportScopeRequest,
        TraceMetadata,
        ValidationError,
        ValidationErrorLocItem,
        VersionedTraceImportAction,
    )
    from .errors import UnprocessableEntityError
    from . import (
        activation,
        agent_imports,
        agents,
        changesets,
        context_registry,
        conversations,
        deployments,
        environments,
        eval_seeds,
        evaluation_comparisons,
        evaluation_criteria,
        evaluation_jobs,
        evaluation_results,
        evaluator_runs,
        execution_objectives,
        execution_sessions,
        executions,
        feedback,
        harness_versions,
        harnesses,
        import_sessions,
        issue_clusters,
        judge_alignment,
        managed_agents,
        memory_registry,
        model_gateway,
        model_settings,
        online_evaluations,
        release_watches,
        retention_policies,
        review_queue,
        run_schedules,
        run_webhooks,
        runs,
        sessions,
        tool_providers,
        trace_import_connections,
        trace_imports,
        trace_streams,
        workflow_intents,
        workflow_runs,
        workflows,
    )
    from ._default_clients import DefaultAioHttpClient, DefaultAsyncHttpxClient
    from .changesets import ListChangesetsChangesetsRequestStatus
    from .client import AsyncSikaruApi, SikaruApi
    from .context_registry import CreateContextRegistryChangeRequestAction
    from .conversations import DeliveredMessageEnvironment, DeliveredMessageRole
    from .environment import SikaruEnvironment
    from .evaluation_jobs import JobInputEnvironment
    from .evaluation_results import (
        EvaluationResultEnvironment,
        EvaluationResultSource,
        EvaluationResultVerdict,
        ListResultsEvaluationResultsRequestEnvironment,
        ListResultsEvaluationResultsRequestVerdict,
    )
    from .execution_sessions import (
        SessionInputReasoningEffort,
        TurnInputDeliveryMode,
        TurnInputExecutionEnvironment,
        TurnInputRunMode,
    )
    from .feedback import CreateFeedbackRequestKind, CreateFeedbackRequestTarget
    from .harness_versions import CreateHarnessVersionRequestStatus
    from .harnesses import ImprovementInputObjective
    from .import_sessions import (
        CreateImportSessionRequestMode,
        CreateSourceArtifactRequestExportPolicy,
        CreateSourceArtifactRequestSourceKind,
    )
    from .judge_alignment import GetJudgeAlignmentJudgeAlignmentRequestEnvironment
    from .managed_agents import CreateManagedAgentRequestStatus
    from .memory_registry import CreateMemoryRegistryChangeRequestAction
    from .online_evaluations import PolicyInputEnvironment, PreviewPolicyEligibilityOnlineEvaluationsRequestEnvironment
    from .review_queue import CreateReviewQueueItemRequestAction
    from .runs import (
        ApprovalInputDecision,
        StartHarnessRunRequestExecutionEnvironment,
        StartHarnessRunRequestRunMode,
        SubmitToolResultRequestStatus,
    )
    from .trace_imports import (
        CreateTraceImportRequestMode,
        CreateTraceImportRequestProvider,
        PlanTraceImportRequestMode,
        PlanTraceImportRequestProvider,
    )
    from .trace_streams import TraceStreamRequestFormat
    from .version import __version__
    from .workflows import CreateWorkflowVersionRequestReleaseChannel, CreateWorkflowVersionRequestStatus
_dynamic_imports: typing.Dict[str, str] = {
    "AgentImportEvalSuiteRequest": ".types",
    "AgentImportImproveRequest": ".types",
    "AgentImportModelCaptureRequest": ".types",
    "AgentImportRunnerRequest": ".types",
    "AgentImportSourceRefRequest": ".types",
    "AgentImportSourceRefRequestExportPolicy": ".types",
    "AnswerRef": ".types",
    "ApprovalInputDecision": ".runs",
    "AsyncSikaruApi": ".client",
    "CaseInput": ".types",
    "CreateContextRegistryChangeRequestAction": ".context_registry",
    "CreateFeedbackRequestKind": ".feedback",
    "CreateFeedbackRequestTarget": ".feedback",
    "CreateHarnessVersionRequestStatus": ".harness_versions",
    "CreateImportSessionRequestMode": ".import_sessions",
    "CreateManagedAgentRequestStatus": ".managed_agents",
    "CreateManagedAgentSourceRequest": ".types",
    "CreateManagedAgentSourceRequestExportPolicy": ".types",
    "CreateManagedAgentSourceRequestSourceKind": ".types",
    "CreateMemoryRegistryChangeRequestAction": ".memory_registry",
    "CreateParityRunRequest": ".types",
    "CreateReviewQueueItemRequestAction": ".review_queue",
    "CreateSourceArtifactRequestExportPolicy": ".import_sessions",
    "CreateSourceArtifactRequestSourceKind": ".import_sessions",
    "CreateTraceImportRequestMode": ".trace_imports",
    "CreateTraceImportRequestProvider": ".trace_imports",
    "CreateWorkflowVersionRequestReleaseChannel": ".workflows",
    "CreateWorkflowVersionRequestStatus": ".workflows",
    "DefaultAioHttpClient": "._default_clients",
    "DefaultAsyncHttpxClient": "._default_clients",
    "DeliveredMessageEnvironment": ".conversations",
    "DeliveredMessageRole": ".conversations",
    "EvaluationResultEnvironment": ".evaluation_results",
    "EvaluationResultSource": ".evaluation_results",
    "EvaluationResultVerdict": ".evaluation_results",
    "EventDeliveryRequest": ".types",
    "GetJudgeAlignmentJudgeAlignmentRequestEnvironment": ".judge_alignment",
    "HttpValidationError": ".types",
    "ImprovementInputObjective": ".harnesses",
    "JobInputEnvironment": ".evaluation_jobs",
    "JudgmentContext": ".types",
    "JudgmentTarget": ".types",
    "JudgmentTargetKind": ".types",
    "ListChangesetsChangesetsRequestStatus": ".changesets",
    "ListResultsEvaluationResultsRequestEnvironment": ".evaluation_results",
    "ListResultsEvaluationResultsRequestVerdict": ".evaluation_results",
    "ManagedRun": ".types",
    "OpenInferenceSpan": ".types",
    "PlanTraceImportRequestMode": ".trace_imports",
    "PlanTraceImportRequestProvider": ".trace_imports",
    "PolicyInputEnvironment": ".online_evaluations",
    "PreviewPolicyEligibilityOnlineEvaluationsRequestEnvironment": ".online_evaluations",
    "RecoverRunRequest": ".types",
    "ReleaseActionRequest": ".types",
    "ResumeImprovementInput": ".types",
    "ResumeInput": ".types",
    "RunEvent": ".types",
    "RunEvents": ".types",
    "ScopeType": ".types",
    "SessionInputReasoningEffort": ".execution_sessions",
    "SikaruApi": ".client",
    "SikaruEnvironment": ".environment",
    "SourceType": ".types",
    "StartHarnessRunRequestExecutionEnvironment": ".runs",
    "StartHarnessRunRequestRunMode": ".runs",
    "SubmitToolResultRequestStatus": ".runs",
    "TargetInput": ".types",
    "ToolProviderRefRequest": ".types",
    "ToolSkillSourceRequest": ".types",
    "TraceImportGroupingRequest": ".types",
    "TraceImportOptionsRequest": ".types",
    "TraceImportScopeRequest": ".types",
    "TraceMetadata": ".types",
    "TraceStreamRequestFormat": ".trace_streams",
    "TurnInputDeliveryMode": ".execution_sessions",
    "TurnInputExecutionEnvironment": ".execution_sessions",
    "TurnInputRunMode": ".execution_sessions",
    "UnprocessableEntityError": ".errors",
    "ValidationError": ".types",
    "ValidationErrorLocItem": ".types",
    "VersionedTraceImportAction": ".types",
    "__version__": ".version",
    "activation": ".activation",
    "agent_imports": ".agent_imports",
    "agents": ".agents",
    "changesets": ".changesets",
    "context_registry": ".context_registry",
    "conversations": ".conversations",
    "deployments": ".deployments",
    "environments": ".environments",
    "eval_seeds": ".eval_seeds",
    "evaluation_comparisons": ".evaluation_comparisons",
    "evaluation_criteria": ".evaluation_criteria",
    "evaluation_jobs": ".evaluation_jobs",
    "evaluation_results": ".evaluation_results",
    "evaluator_runs": ".evaluator_runs",
    "execution_objectives": ".execution_objectives",
    "execution_sessions": ".execution_sessions",
    "executions": ".executions",
    "feedback": ".feedback",
    "harness_versions": ".harness_versions",
    "harnesses": ".harnesses",
    "import_sessions": ".import_sessions",
    "issue_clusters": ".issue_clusters",
    "judge_alignment": ".judge_alignment",
    "managed_agents": ".managed_agents",
    "memory_registry": ".memory_registry",
    "model_gateway": ".model_gateway",
    "model_settings": ".model_settings",
    "online_evaluations": ".online_evaluations",
    "release_watches": ".release_watches",
    "retention_policies": ".retention_policies",
    "review_queue": ".review_queue",
    "run_schedules": ".run_schedules",
    "run_webhooks": ".run_webhooks",
    "runs": ".runs",
    "sessions": ".sessions",
    "tool_providers": ".tool_providers",
    "trace_import_connections": ".trace_import_connections",
    "trace_imports": ".trace_imports",
    "trace_streams": ".trace_streams",
    "workflow_intents": ".workflow_intents",
    "workflow_runs": ".workflow_runs",
    "workflows": ".workflows",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AgentImportEvalSuiteRequest",
    "AgentImportImproveRequest",
    "AgentImportModelCaptureRequest",
    "AgentImportRunnerRequest",
    "AgentImportSourceRefRequest",
    "AgentImportSourceRefRequestExportPolicy",
    "AnswerRef",
    "ApprovalInputDecision",
    "AsyncSikaruApi",
    "CaseInput",
    "CreateContextRegistryChangeRequestAction",
    "CreateFeedbackRequestKind",
    "CreateFeedbackRequestTarget",
    "CreateHarnessVersionRequestStatus",
    "CreateImportSessionRequestMode",
    "CreateManagedAgentRequestStatus",
    "CreateManagedAgentSourceRequest",
    "CreateManagedAgentSourceRequestExportPolicy",
    "CreateManagedAgentSourceRequestSourceKind",
    "CreateMemoryRegistryChangeRequestAction",
    "CreateParityRunRequest",
    "CreateReviewQueueItemRequestAction",
    "CreateSourceArtifactRequestExportPolicy",
    "CreateSourceArtifactRequestSourceKind",
    "CreateTraceImportRequestMode",
    "CreateTraceImportRequestProvider",
    "CreateWorkflowVersionRequestReleaseChannel",
    "CreateWorkflowVersionRequestStatus",
    "DefaultAioHttpClient",
    "DefaultAsyncHttpxClient",
    "DeliveredMessageEnvironment",
    "DeliveredMessageRole",
    "EvaluationResultEnvironment",
    "EvaluationResultSource",
    "EvaluationResultVerdict",
    "EventDeliveryRequest",
    "GetJudgeAlignmentJudgeAlignmentRequestEnvironment",
    "HttpValidationError",
    "ImprovementInputObjective",
    "JobInputEnvironment",
    "JudgmentContext",
    "JudgmentTarget",
    "JudgmentTargetKind",
    "ListChangesetsChangesetsRequestStatus",
    "ListResultsEvaluationResultsRequestEnvironment",
    "ListResultsEvaluationResultsRequestVerdict",
    "ManagedRun",
    "OpenInferenceSpan",
    "PlanTraceImportRequestMode",
    "PlanTraceImportRequestProvider",
    "PolicyInputEnvironment",
    "PreviewPolicyEligibilityOnlineEvaluationsRequestEnvironment",
    "RecoverRunRequest",
    "ReleaseActionRequest",
    "ResumeImprovementInput",
    "ResumeInput",
    "RunEvent",
    "RunEvents",
    "ScopeType",
    "SessionInputReasoningEffort",
    "SikaruApi",
    "SikaruEnvironment",
    "SourceType",
    "StartHarnessRunRequestExecutionEnvironment",
    "StartHarnessRunRequestRunMode",
    "SubmitToolResultRequestStatus",
    "TargetInput",
    "ToolProviderRefRequest",
    "ToolSkillSourceRequest",
    "TraceImportGroupingRequest",
    "TraceImportOptionsRequest",
    "TraceImportScopeRequest",
    "TraceMetadata",
    "TraceStreamRequestFormat",
    "TurnInputDeliveryMode",
    "TurnInputExecutionEnvironment",
    "TurnInputRunMode",
    "UnprocessableEntityError",
    "ValidationError",
    "ValidationErrorLocItem",
    "VersionedTraceImportAction",
    "__version__",
    "activation",
    "agent_imports",
    "agents",
    "changesets",
    "context_registry",
    "conversations",
    "deployments",
    "environments",
    "eval_seeds",
    "evaluation_comparisons",
    "evaluation_criteria",
    "evaluation_jobs",
    "evaluation_results",
    "evaluator_runs",
    "execution_objectives",
    "execution_sessions",
    "executions",
    "feedback",
    "harness_versions",
    "harnesses",
    "import_sessions",
    "issue_clusters",
    "judge_alignment",
    "managed_agents",
    "memory_registry",
    "model_gateway",
    "model_settings",
    "online_evaluations",
    "release_watches",
    "retention_policies",
    "review_queue",
    "run_schedules",
    "run_webhooks",
    "runs",
    "sessions",
    "tool_providers",
    "trace_import_connections",
    "trace_imports",
    "trace_streams",
    "workflow_intents",
    "workflow_runs",
    "workflows",
]
