// This file was auto-generated by Fern from our API Definition.

import * as Sikaru from "../../../../index.js";

/**
 * @example
 *     {
 *         config: {},
 *         display_name: "display_name",
 *         kind: "mcp"
 *     }
 */
export interface CreateConnection {
    config: Sikaru.ConnectionConfig;
    credentials?: Sikaru.ConnectionCredentials;
    display_name: string;
    kind: CreateConnection.Kind;
    ownership?: CreateConnection.Ownership;
}

export namespace CreateConnection {
    export const Kind = {
            Mcp: "mcp",
            Composio: "composio"
        } as const;
    export type Kind = typeof Kind[keyof typeof Kind];
    export const Ownership = {
            Workspace: "workspace",
            Personal: "personal"
        } as const;
    export type Ownership = typeof Ownership[keyof typeof Ownership];
}
