// This file was auto-generated by Fern from our API Definition.

import * as Sikaru from "../../src/api/index";
import { SikaruApi } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ComputeOperationsClient", () => {
    
    test("submit_receipt (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SikaruApi({ "maxRetries" : 0 , "apiKey" : "test" , "environment" : server.baseUrl });
        const rawRequestBody = { "idempotency_key" : "idempotency_key" , "payload" : { "key" : "value" } , "request_digest" : "request_digest" , "run_id" : "run_id" , "status" : "completed" , "tool_call_id" : "tool_call_id" , "tool_provider_id" : "tool_provider_id" };
        const rawResponseBody = { "created" : true , "status" : "accepted" , "tool_call_id" : "tool_call_id" };
        
        server
            .mockEndpoint()
            .post("/v1/projects/project_id/compute-attachments/attachment_id/receipts").jsonBody(rawRequestBody)
                .respondWith()
            .statusCode(200).jsonBody(rawResponseBody)
                .build();

        
                        
                                const response = await client.computeOperations.submitReceipt("project_id", "attachment_id", {
    idempotency_key: "idempotency_key",
    payload: {
        "key": "value"
    },
    request_digest: "request_digest",
    run_id: "run_id",
    status: "completed",
    tool_call_id: "tool_call_id",
    tool_provider_id: "tool_provider_id"
});
                                expect(response).toEqual(rawResponseBody);
                              
                    
    });
          
    test("submit_receipt (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SikaruApi({ "maxRetries" : 0 , "apiKey" : "test" , "environment" : server.baseUrl });
        const rawRequestBody = { "idempotency_key" : "x" , "payload" : { "payload" : { "key" : "value" } } , "request_digest" : "request_digest" , "run_id" : "x" , "status" : "completed" , "tool_call_id" : "x" , "tool_provider_id" : "x" };
        const rawResponseBody = { "detail" : "detail" };
        
        server
            .mockEndpoint()
            .post("/v1/projects/project_id/compute-attachments/attachment_id/receipts").jsonBody(rawRequestBody)
                .respondWith()
            .statusCode(401).jsonBody(rawResponseBody)
                .build();

        
            await expect(async () => {
                return await client.computeOperations.submitReceipt("project_id", "attachment_id", {
    idempotency_key: "x",
    payload: {
        "payload": {
            "key": "value"
        }
    },
    request_digest: "request_digest",
    run_id: "x",
    status: "completed",
    tool_call_id: "x",
    tool_provider_id: "x"
})
            }).rejects.toThrow(Sikaru.UnauthorizedError);
    });
          
    test("submit_receipt (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SikaruApi({ "maxRetries" : 0 , "apiKey" : "test" , "environment" : server.baseUrl });
        const rawRequestBody = { "idempotency_key" : "x" , "payload" : { "payload" : { "key" : "value" } } , "request_digest" : "request_digest" , "run_id" : "x" , "status" : "completed" , "tool_call_id" : "x" , "tool_provider_id" : "x" };
        const rawResponseBody = { "detail" : "detail" };
        
        server
            .mockEndpoint()
            .post("/v1/projects/project_id/compute-attachments/attachment_id/receipts").jsonBody(rawRequestBody)
                .respondWith()
            .statusCode(403).jsonBody(rawResponseBody)
                .build();

        
            await expect(async () => {
                return await client.computeOperations.submitReceipt("project_id", "attachment_id", {
    idempotency_key: "x",
    payload: {
        "payload": {
            "key": "value"
        }
    },
    request_digest: "request_digest",
    run_id: "x",
    status: "completed",
    tool_call_id: "x",
    tool_provider_id: "x"
})
            }).rejects.toThrow(Sikaru.ForbiddenError);
    });
          
    test("submit_receipt (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SikaruApi({ "maxRetries" : 0 , "apiKey" : "test" , "environment" : server.baseUrl });
        const rawRequestBody = { "idempotency_key" : "x" , "payload" : { "payload" : { "key" : "value" } } , "request_digest" : "request_digest" , "run_id" : "x" , "status" : "completed" , "tool_call_id" : "x" , "tool_provider_id" : "x" };
        const rawResponseBody = { "detail" : "detail" };
        
        server
            .mockEndpoint()
            .post("/v1/projects/project_id/compute-attachments/attachment_id/receipts").jsonBody(rawRequestBody)
                .respondWith()
            .statusCode(404).jsonBody(rawResponseBody)
                .build();

        
            await expect(async () => {
                return await client.computeOperations.submitReceipt("project_id", "attachment_id", {
    idempotency_key: "x",
    payload: {
        "payload": {
            "key": "value"
        }
    },
    request_digest: "request_digest",
    run_id: "x",
    status: "completed",
    tool_call_id: "x",
    tool_provider_id: "x"
})
            }).rejects.toThrow(Sikaru.NotFoundError);
    });
          
    test("submit_receipt (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SikaruApi({ "maxRetries" : 0 , "apiKey" : "test" , "environment" : server.baseUrl });
        const rawRequestBody = { "idempotency_key" : "x" , "payload" : { "payload" : { "key" : "value" } } , "request_digest" : "request_digest" , "run_id" : "x" , "status" : "completed" , "tool_call_id" : "x" , "tool_provider_id" : "x" };
        const rawResponseBody = { "detail" : "detail" };
        
        server
            .mockEndpoint()
            .post("/v1/projects/project_id/compute-attachments/attachment_id/receipts").jsonBody(rawRequestBody)
                .respondWith()
            .statusCode(409).jsonBody(rawResponseBody)
                .build();

        
            await expect(async () => {
                return await client.computeOperations.submitReceipt("project_id", "attachment_id", {
    idempotency_key: "x",
    payload: {
        "payload": {
            "key": "value"
        }
    },
    request_digest: "request_digest",
    run_id: "x",
    status: "completed",
    tool_call_id: "x",
    tool_provider_id: "x"
})
            }).rejects.toThrow(Sikaru.ConflictError);
    });
          
    test("submit_receipt (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new SikaruApi({ "maxRetries" : 0 , "apiKey" : "test" , "environment" : server.baseUrl });
        const rawRequestBody = { "idempotency_key" : "x" , "payload" : { "payload" : { "key" : "value" } } , "request_digest" : "request_digest" , "run_id" : "x" , "status" : "completed" , "tool_call_id" : "x" , "tool_provider_id" : "x" };
        const rawResponseBody = { };
        
        server
            .mockEndpoint()
            .post("/v1/projects/project_id/compute-attachments/attachment_id/receipts").jsonBody(rawRequestBody)
                .respondWith()
            .statusCode(422).jsonBody(rawResponseBody)
                .build();

        
            await expect(async () => {
                return await client.computeOperations.submitReceipt("project_id", "attachment_id", {
    idempotency_key: "x",
    payload: {
        "payload": {
            "key": "value"
        }
    },
    request_digest: "request_digest",
    run_id: "x",
    status: "completed",
    tool_call_id: "x",
    tool_provider_id: "x"
})
            }).rejects.toThrow(Sikaru.UnprocessableEntityError);
    });
          
    test("submit_receipt (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new SikaruApi({ "maxRetries" : 0 , "apiKey" : "test" , "environment" : server.baseUrl });
        const rawRequestBody = { "idempotency_key" : "x" , "payload" : { "payload" : { "key" : "value" } } , "request_digest" : "request_digest" , "run_id" : "x" , "status" : "completed" , "tool_call_id" : "x" , "tool_provider_id" : "x" };
        const rawResponseBody = { "detail" : "detail" };
        
        server
            .mockEndpoint()
            .post("/v1/projects/project_id/compute-attachments/attachment_id/receipts").jsonBody(rawRequestBody)
                .respondWith()
            .statusCode(503).jsonBody(rawResponseBody)
                .build();

        
            await expect(async () => {
                return await client.computeOperations.submitReceipt("project_id", "attachment_id", {
    idempotency_key: "x",
    payload: {
        "payload": {
            "key": "value"
        }
    },
    request_digest: "request_digest",
    run_id: "x",
    status: "completed",
    tool_call_id: "x",
    tool_provider_id: "x"
})
            }).rejects.toThrow(Sikaru.ServiceUnavailableError);
    });
          
    test("poll (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SikaruApi({ "maxRetries" : 0 , "apiKey" : "test" , "environment" : server.baseUrl });
        
        const rawResponseBody = { "attachment" : { "capabilities" : [ "capabilities" ] , "cleanup_at" : 1.1 , "cleanup_status" : "unconfirmed" , "environment_id" : "environment_id" , "id" : "id" , "journal_id" : "journal_id" , "lease_ttl_seconds" : 1 , "lease_until" : 1.1 , "owner_epoch" : 1 , "owner_id" : "owner_id" , "processes" : [ { "evidence" : "evidence" , "handle_id" : "handle_id" , "status" : "running" } ] , "project_id" : "project_id" , "protocol_version" : "protocol_version" , "provider_id" : "provider_id" , "session_id" : "session_id" , "startup_deadline" : 1.1 , "status" : "pending" , "uncertain_operations" : [ { "method" : "method" , "owner_epoch" : 1 , "request_digest" : "request_digest" , "run_id" : "run_id" , "tool_call_id" : "tool_call_id" , "workspace_generation" : "workspace_generation" } ] , "workspace_generation" : "workspace_generation" , "workspace_provenance" : { "identity" : "identity" , "kind" : "existing_directory" } } , "execution" : { "approval_required" : true , "run_id" : "run_id" , "status" : "status" , "terminal" : true } , "execution_phase" : "idle" , "issued_operations" : [ { "method" : "method" , "owner_epoch" : 1 , "request_digest" : "request_digest" , "run_id" : "run_id" , "tool_call_id" : "tool_call_id" , "workspace_generation" : "workspace_generation" } ] , "live_handles" : [ { "handle_id" : "handle_id" , "run_id" : "run_id" , "tool_call_id" : "tool_call_id" } ] , "operations" : [ { "arguments" : { "key" : "value" } , "capability_name" : "compute.execute" , "method" : "bash.run" , "owner_epoch" : 1 , "request_digest" : "request_digest" , "run_id" : "run_id" , "tool_call_id" : "tool_call_id" , "tool_provider_id" : "tool_provider_id" , "workspace_generation" : "workspace_generation" } ] , "poll_after_seconds" : 1 , "workspace_checkpoint" : { "checkpoint_id" : "checkpoint_id" , "owner_epoch" : 1 , "run_id" : "run_id" , "status" : "requested" , "tree_id" : "tree_id" , "workspace_generation" : "workspace_generation" } };
        
        server
            .mockEndpoint()
            .get("/v1/projects/project_id/compute-attachments/attachment_id/work").respondWith()
            .statusCode(200).jsonBody(rawResponseBody)
                .build();

        
                        
                                const response = await client.computeOperations.poll("project_id", "attachment_id");
                                expect(response).toEqual(rawResponseBody);
                              
                    
    });
          
    test("poll (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SikaruApi({ "maxRetries" : 0 , "apiKey" : "test" , "environment" : server.baseUrl });
        
        const rawResponseBody = { "detail" : "detail" };
        
        server
            .mockEndpoint()
            .get("/v1/projects/project_id/compute-attachments/attachment_id/work").respondWith()
            .statusCode(401).jsonBody(rawResponseBody)
                .build();

        
            await expect(async () => {
                return await client.computeOperations.poll("project_id", "attachment_id")
            }).rejects.toThrow(Sikaru.UnauthorizedError);
    });
          
    test("poll (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SikaruApi({ "maxRetries" : 0 , "apiKey" : "test" , "environment" : server.baseUrl });
        
        const rawResponseBody = { "detail" : "detail" };
        
        server
            .mockEndpoint()
            .get("/v1/projects/project_id/compute-attachments/attachment_id/work").respondWith()
            .statusCode(403).jsonBody(rawResponseBody)
                .build();

        
            await expect(async () => {
                return await client.computeOperations.poll("project_id", "attachment_id")
            }).rejects.toThrow(Sikaru.ForbiddenError);
    });
          
    test("poll (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SikaruApi({ "maxRetries" : 0 , "apiKey" : "test" , "environment" : server.baseUrl });
        
        const rawResponseBody = { "detail" : "detail" };
        
        server
            .mockEndpoint()
            .get("/v1/projects/project_id/compute-attachments/attachment_id/work").respondWith()
            .statusCode(404).jsonBody(rawResponseBody)
                .build();

        
            await expect(async () => {
                return await client.computeOperations.poll("project_id", "attachment_id")
            }).rejects.toThrow(Sikaru.NotFoundError);
    });
          
    test("poll (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SikaruApi({ "maxRetries" : 0 , "apiKey" : "test" , "environment" : server.baseUrl });
        
        const rawResponseBody = { "detail" : "detail" };
        
        server
            .mockEndpoint()
            .get("/v1/projects/project_id/compute-attachments/attachment_id/work").respondWith()
            .statusCode(409).jsonBody(rawResponseBody)
                .build();

        
            await expect(async () => {
                return await client.computeOperations.poll("project_id", "attachment_id")
            }).rejects.toThrow(Sikaru.ConflictError);
    });
          
    test("poll (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new SikaruApi({ "maxRetries" : 0 , "apiKey" : "test" , "environment" : server.baseUrl });
        
        const rawResponseBody = { };
        
        server
            .mockEndpoint()
            .get("/v1/projects/project_id/compute-attachments/attachment_id/work").respondWith()
            .statusCode(422).jsonBody(rawResponseBody)
                .build();

        
            await expect(async () => {
                return await client.computeOperations.poll("project_id", "attachment_id")
            }).rejects.toThrow(Sikaru.UnprocessableEntityError);
    });
          
    test("poll (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new SikaruApi({ "maxRetries" : 0 , "apiKey" : "test" , "environment" : server.baseUrl });
        
        const rawResponseBody = { "detail" : "detail" };
        
        server
            .mockEndpoint()
            .get("/v1/projects/project_id/compute-attachments/attachment_id/work").respondWith()
            .statusCode(503).jsonBody(rawResponseBody)
                .build();

        
            await expect(async () => {
                return await client.computeOperations.poll("project_id", "attachment_id")
            }).rejects.toThrow(Sikaru.ServiceUnavailableError);
    });
          
});
