// This file was auto-generated by Fern from our API Definition.

import * as Sikaru from "../../src/api/index";
import { SikaruApi } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("SessionsClient", () => {
    
    test("get_managed_session (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SikaruApi({ "maxRetries" : 0 , "apiKey" : "test" , "environment" : server.baseUrl });
        
        const rawResponseBody = { "key" : "value" };
        
        server
            .mockEndpoint()
            .get("/v1/projects/project_id/sessions/session_id").respondWith()
            .statusCode(200).jsonBody(rawResponseBody)
                .build();

        
                        
                                const response = await client.sessions.getManagedSession("project_id", "session_id");
                                expect(response).toEqual(rawResponseBody);
                              
                    
    });
          
    test("get_managed_session (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SikaruApi({ "maxRetries" : 0 , "apiKey" : "test" , "environment" : server.baseUrl });
        
        const rawResponseBody = { };
        
        server
            .mockEndpoint()
            .get("/v1/projects/project_id/sessions/session_id").respondWith()
            .statusCode(422).jsonBody(rawResponseBody)
                .build();

        
            await expect(async () => {
                return await client.sessions.getManagedSession("project_id", "session_id")
            }).rejects.toThrow(Sikaru.UnprocessableEntityError);
    });
          
    test("list_managed_session_events (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SikaruApi({ "maxRetries" : 0 , "apiKey" : "test" , "environment" : server.baseUrl });
        
        const rawResponseBody = { "key" : "value" };
        
        server
            .mockEndpoint()
            .get("/v1/projects/project_id/sessions/session_id/events").respondWith()
            .statusCode(200).jsonBody(rawResponseBody)
                .build();

        
                        
                                const response = await client.sessions.listManagedSessionEvents("project_id", "session_id");
                                expect(response).toEqual(rawResponseBody);
                              
                    
    });
          
    test("list_managed_session_events (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SikaruApi({ "maxRetries" : 0 , "apiKey" : "test" , "environment" : server.baseUrl });
        
        const rawResponseBody = { };
        
        server
            .mockEndpoint()
            .get("/v1/projects/project_id/sessions/session_id/events").respondWith()
            .statusCode(422).jsonBody(rawResponseBody)
                .build();

        
            await expect(async () => {
                return await client.sessions.listManagedSessionEvents("project_id", "session_id")
            }).rejects.toThrow(Sikaru.UnprocessableEntityError);
    });
          
    test("list_managed_session_files (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SikaruApi({ "maxRetries" : 0 , "apiKey" : "test" , "environment" : server.baseUrl });
        
        const rawResponseBody = { "key" : "value" };
        
        server
            .mockEndpoint()
            .get("/v1/projects/project_id/sessions/session_id/files").respondWith()
            .statusCode(200).jsonBody(rawResponseBody)
                .build();

        
                        
                                const response = await client.sessions.listManagedSessionFiles("project_id", "session_id");
                                expect(response).toEqual(rawResponseBody);
                              
                    
    });
          
    test("list_managed_session_files (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SikaruApi({ "maxRetries" : 0 , "apiKey" : "test" , "environment" : server.baseUrl });
        
        const rawResponseBody = { };
        
        server
            .mockEndpoint()
            .get("/v1/projects/project_id/sessions/session_id/files").respondWith()
            .statusCode(422).jsonBody(rawResponseBody)
                .build();

        
            await expect(async () => {
                return await client.sessions.listManagedSessionFiles("project_id", "session_id")
            }).rejects.toThrow(Sikaru.UnprocessableEntityError);
    });
          
    test("list_managed_session_plan (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SikaruApi({ "maxRetries" : 0 , "apiKey" : "test" , "environment" : server.baseUrl });
        
        const rawResponseBody = { "key" : "value" };
        
        server
            .mockEndpoint()
            .get("/v1/projects/project_id/sessions/session_id/plan").respondWith()
            .statusCode(200).jsonBody(rawResponseBody)
                .build();

        
                        
                                const response = await client.sessions.listManagedSessionPlan("project_id", "session_id");
                                expect(response).toEqual(rawResponseBody);
                              
                    
    });
          
    test("list_managed_session_plan (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SikaruApi({ "maxRetries" : 0 , "apiKey" : "test" , "environment" : server.baseUrl });
        
        const rawResponseBody = { };
        
        server
            .mockEndpoint()
            .get("/v1/projects/project_id/sessions/session_id/plan").respondWith()
            .statusCode(422).jsonBody(rawResponseBody)
                .build();

        
            await expect(async () => {
                return await client.sessions.listManagedSessionPlan("project_id", "session_id")
            }).rejects.toThrow(Sikaru.UnprocessableEntityError);
    });
          
});
