// This file was auto-generated by Fern from our API Definition.

import * as Sikaru from "../../../../index.js";

/**
 * @example
 *     {
 *         body: {
 *             state: "state"
 *         }
 *     }
 */
export interface CompleteConnectionPersonalChannelsRequest {
    authorization?: string | null;
    "X-Sikaru-User-Assertion"?: string | null;
    "X-Sikaru-Member-Authorization"?: string | null;
    body: Sikaru.CompleteAuthorization;
}
