// Code generated by Fern. DO NOT EDIT.

package harnesses

import (
	context "context"
	os "os"

	_go "github.com/aadi-labs/sikaru-sdk/go"
	core "github.com/aadi-labs/sikaru-sdk/go/core"
	internal "github.com/aadi-labs/sikaru-sdk/go/internal"
	option "github.com/aadi-labs/sikaru-sdk/go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.APIKey == "" {
		options.APIKey = os.Getenv("SIKARU_API_KEY")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Example:
//
//	client.Harnesses.GetInvoiceBudget(
//	    context.TODO(),
//	    "project_id",
//	    "harness_id",
//	)
func (c *Client) GetInvoiceBudget(
	ctx context.Context,
	projectID string,
	harnessID string,
	opts ...option.RequestOption,
) (*_go.InvoiceBudget, error) {
	response, err := c.WithRawResponse.GetInvoiceBudget(
		ctx,
		projectID,
		harnessID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	client.Harnesses.GetSubscription(
//	    context.TODO(),
//	    "project_id",
//	    "harness_id",
//	)
func (c *Client) GetSubscription(
	ctx context.Context,
	projectID string,
	harnessID string,
	opts ...option.RequestOption,
) (*_go.SubscriptionStatus, error) {
	response, err := c.WithRawResponse.GetSubscription(
		ctx,
		projectID,
		harnessID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &_go.SubscriptionInput{
//	    AcceptedRecurringTerms: true,
//	    IdempotencyKey: "idempotency_key",
//	    Plan: _go.SubscriptionInputPlanBuild,
//	}
//	client.Harnesses.Subscribe(
//	    context.TODO(),
//	    "project_id",
//	    "harness_id",
//	    request,
//	)
func (c *Client) Subscribe(
	ctx context.Context,
	projectID string,
	harnessID string,
	request *_go.SubscriptionInput,
	opts ...option.RequestOption,
) (*_go.SubscriptionSetup, error) {
	response, err := c.WithRawResponse.Subscribe(
		ctx,
		projectID,
		harnessID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	client.Harnesses.CancelSubscription(
//	    context.TODO(),
//	    "project_id",
//	    "harness_id",
//	)
func (c *Client) CancelSubscription(
	ctx context.Context,
	projectID string,
	harnessID string,
	opts ...option.RequestOption,
) (*_go.SubscriptionCancellation, error) {
	response, err := c.WithRawResponse.CancelSubscription(
		ctx,
		projectID,
		harnessID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	client.Harnesses.ImprovementOptions(
//	    context.TODO(),
//	    "project_id",
//	    "harness_id",
//	)
func (c *Client) ImprovementOptions(
	ctx context.Context,
	projectID string,
	harnessID string,
	opts ...option.RequestOption,
) (map[string]any, error) {
	response, err := c.WithRawResponse.ImprovementOptions(
		ctx,
		projectID,
		harnessID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &_go.ListImprovementsHarnessesRequest{}
//	client.Harnesses.ListImprovements(
//	    context.TODO(),
//	    "project_id",
//	    "harness_id",
//	    request,
//	)
func (c *Client) ListImprovements(
	ctx context.Context,
	projectID string,
	harnessID string,
	request *_go.ListImprovementsHarnessesRequest,
	opts ...option.RequestOption,
) (map[string]any, error) {
	response, err := c.WithRawResponse.ListImprovements(
		ctx,
		projectID,
		harnessID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &_go.ImprovementInput{
//	    IdempotencyKey: "idempotency_key",
//	}
//	client.Harnesses.StartImprovement(
//	    context.TODO(),
//	    "project_id",
//	    "harness_id",
//	    request,
//	)
func (c *Client) StartImprovement(
	ctx context.Context,
	projectID string,
	harnessID string,
	request *_go.ImprovementInput,
	opts ...option.RequestOption,
) (map[string]any, error) {
	response, err := c.WithRawResponse.StartImprovement(
		ctx,
		projectID,
		harnessID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	client.Harnesses.GetImprovement(
//	    context.TODO(),
//	    "project_id",
//	    "harness_id",
//	    "job_id",
//	)
func (c *Client) GetImprovement(
	ctx context.Context,
	projectID string,
	harnessID string,
	jobID string,
	opts ...option.RequestOption,
) (map[string]any, error) {
	response, err := c.WithRawResponse.GetImprovement(
		ctx,
		projectID,
		harnessID,
		jobID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &_go.ResumeImprovementInput{}
//	client.Harnesses.ResumeImprovement(
//	    context.TODO(),
//	    "project_id",
//	    "harness_id",
//	    "job_id",
//	    request,
//	)
func (c *Client) ResumeImprovement(
	ctx context.Context,
	projectID string,
	harnessID string,
	jobID string,
	request *_go.ResumeImprovementInput,
	opts ...option.RequestOption,
) (map[string]any, error) {
	response, err := c.WithRawResponse.ResumeImprovement(
		ctx,
		projectID,
		harnessID,
		jobID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Reserved, unavailable model-training step; no learning job is submitted.
//
// Example:
//
//	client.Harnesses.TrainModelStub(
//	    context.TODO(),
//	    "project_id",
//	    "harness_id",
//	)
func (c *Client) TrainModelStub(
	ctx context.Context,
	projectID string,
	harnessID string,
	opts ...option.RequestOption,
) (map[string]any, error) {
	response, err := c.WithRawResponse.TrainModelStub(
		ctx,
		projectID,
		harnessID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
