// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         selectedModelId: "selectedModelId"
 *     }
 */
export interface ModelSelection {
    selectedModelId: string;
}
