// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         environment_slug: "environment_slug",
 *         idempotency_key: "idempotency_key"
 *     }
 */
export interface EnvironmentInput {
    environment_slug: string;
    idempotency_key: string;
    product_id?: string | null;
    session_id?: string | null;
}
