# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.agent_definition import AgentDefinition
from ..types.create_managed_agent_source_request import CreateManagedAgentSourceRequest
from ..types.created_managed_agent import CreatedManagedAgent
from ..types.definition_revision_result import DefinitionRevisionResult
from ..types.definition_revision_view import DefinitionRevisionView
from ..types.renamed_managed_agent import RenamedManagedAgent
from .raw_client import AsyncRawManagedAgentsClient, RawManagedAgentsClient
from .types.create_managed_agent_request_initial_channel import CreateManagedAgentRequestInitialChannel
from .types.create_managed_agent_request_status import CreateManagedAgentRequestStatus

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ManagedAgentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawManagedAgentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawManagedAgentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawManagedAgentsClient
        """
        return self._raw_client

    def list_managed_agents(
        self, project_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Parameters
        ----------
        project_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.managed_agents.list_managed_agents(
            project_id="project_id",
        )
        """
        _response = self._raw_client.list_managed_agents(project_id, request_options=request_options)
        return _response.data

    def create_managed_agent(
        self,
        project_id: str,
        *,
        agent_slug: str,
        active_harness_version_id: typing.Optional[str] = OMIT,
        compatibility_profile_id: typing.Optional[str] = OMIT,
        display_name: typing.Optional[str] = OMIT,
        harness_id: typing.Optional[str] = OMIT,
        initial_channel: typing.Optional[CreateManagedAgentRequestInitialChannel] = OMIT,
        source: typing.Optional[CreateManagedAgentSourceRequest] = OMIT,
        status: typing.Optional[CreateManagedAgentRequestStatus] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreatedManagedAgent:
        """
        Parameters
        ----------
        project_id : str

        agent_slug : str

        active_harness_version_id : typing.Optional[str]

        compatibility_profile_id : typing.Optional[str]

        display_name : typing.Optional[str]

        harness_id : typing.Optional[str]

        initial_channel : typing.Optional[CreateManagedAgentRequestInitialChannel]

        source : typing.Optional[CreateManagedAgentSourceRequest]

        status : typing.Optional[CreateManagedAgentRequestStatus]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatedManagedAgent
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.managed_agents.create_managed_agent(
            project_id="project_id",
            agent_slug="agentSlug",
        )
        """
        _response = self._raw_client.create_managed_agent(
            project_id,
            agent_slug=agent_slug,
            active_harness_version_id=active_harness_version_id,
            compatibility_profile_id=compatibility_profile_id,
            display_name=display_name,
            harness_id=harness_id,
            initial_channel=initial_channel,
            source=source,
            status=status,
            request_options=request_options,
        )
        return _response.data

    def delete_managed_agent(
        self, project_id: str, agent_slug: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Delete an agent that has never gone live, with its drafts, checks and schedules.

        Parameters
        ----------
        project_id : str

        agent_slug : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.managed_agents.delete_managed_agent(
            project_id="project_id",
            agent_slug="agent_slug",
        )
        """
        _response = self._raw_client.delete_managed_agent(project_id, agent_slug, request_options=request_options)
        return _response.data

    def rename_managed_agent(
        self,
        project_id: str,
        agent_slug: str,
        *,
        display_name: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RenamedManagedAgent:
        """
        Change the agent's display name. The slug and every reference to the agent stay the same.

        Parameters
        ----------
        project_id : str

        agent_slug : str

        display_name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RenamedManagedAgent
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.managed_agents.rename_managed_agent(
            project_id="project_id",
            agent_slug="agent_slug",
            display_name="displayName",
        )
        """
        _response = self._raw_client.rename_managed_agent(
            project_id, agent_slug, display_name=display_name, request_options=request_options
        )
        return _response.data

    def create_definition_revision(
        self,
        project_id: str,
        agent_slug: str,
        *,
        content_digest: str,
        definition: AgentDefinition,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DefinitionRevisionResult:
        """
        Stage a changed definition as a draft revision; the live definition is a no-op.

        Parameters
        ----------
        project_id : str

        agent_slug : str

        content_digest : str

        definition : AgentDefinition

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DefinitionRevisionResult
            Successful Response

        Examples
        --------
        from sikaru_api import AgentDefinition, SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.managed_agents.create_definition_revision(
            project_id="project_id",
            agent_slug="agent_slug",
            content_digest="contentDigest",
            definition=AgentDefinition(
                schema="sikaru.agent.contract.v1",
            ),
        )
        """
        _response = self._raw_client.create_definition_revision(
            project_id,
            agent_slug,
            content_digest=content_digest,
            definition=definition,
            request_options=request_options,
        )
        return _response.data

    def get_definition_revision(
        self,
        project_id: str,
        agent_slug: str,
        changeset_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DefinitionRevisionView:
        """
        Parameters
        ----------
        project_id : str

        agent_slug : str

        changeset_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DefinitionRevisionView
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.managed_agents.get_definition_revision(
            project_id="project_id",
            agent_slug="agent_slug",
            changeset_id="changeset_id",
        )
        """
        _response = self._raw_client.get_definition_revision(
            project_id, agent_slug, changeset_id, request_options=request_options
        )
        return _response.data


class AsyncManagedAgentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawManagedAgentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawManagedAgentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawManagedAgentsClient
        """
        return self._raw_client

    async def list_managed_agents(
        self, project_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Parameters
        ----------
        project_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.managed_agents.list_managed_agents(
                project_id="project_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_managed_agents(project_id, request_options=request_options)
        return _response.data

    async def create_managed_agent(
        self,
        project_id: str,
        *,
        agent_slug: str,
        active_harness_version_id: typing.Optional[str] = OMIT,
        compatibility_profile_id: typing.Optional[str] = OMIT,
        display_name: typing.Optional[str] = OMIT,
        harness_id: typing.Optional[str] = OMIT,
        initial_channel: typing.Optional[CreateManagedAgentRequestInitialChannel] = OMIT,
        source: typing.Optional[CreateManagedAgentSourceRequest] = OMIT,
        status: typing.Optional[CreateManagedAgentRequestStatus] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreatedManagedAgent:
        """
        Parameters
        ----------
        project_id : str

        agent_slug : str

        active_harness_version_id : typing.Optional[str]

        compatibility_profile_id : typing.Optional[str]

        display_name : typing.Optional[str]

        harness_id : typing.Optional[str]

        initial_channel : typing.Optional[CreateManagedAgentRequestInitialChannel]

        source : typing.Optional[CreateManagedAgentSourceRequest]

        status : typing.Optional[CreateManagedAgentRequestStatus]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatedManagedAgent
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.managed_agents.create_managed_agent(
                project_id="project_id",
                agent_slug="agentSlug",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_managed_agent(
            project_id,
            agent_slug=agent_slug,
            active_harness_version_id=active_harness_version_id,
            compatibility_profile_id=compatibility_profile_id,
            display_name=display_name,
            harness_id=harness_id,
            initial_channel=initial_channel,
            source=source,
            status=status,
            request_options=request_options,
        )
        return _response.data

    async def delete_managed_agent(
        self, project_id: str, agent_slug: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Delete an agent that has never gone live, with its drafts, checks and schedules.

        Parameters
        ----------
        project_id : str

        agent_slug : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.managed_agents.delete_managed_agent(
                project_id="project_id",
                agent_slug="agent_slug",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_managed_agent(project_id, agent_slug, request_options=request_options)
        return _response.data

    async def rename_managed_agent(
        self,
        project_id: str,
        agent_slug: str,
        *,
        display_name: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RenamedManagedAgent:
        """
        Change the agent's display name. The slug and every reference to the agent stay the same.

        Parameters
        ----------
        project_id : str

        agent_slug : str

        display_name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RenamedManagedAgent
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.managed_agents.rename_managed_agent(
                project_id="project_id",
                agent_slug="agent_slug",
                display_name="displayName",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.rename_managed_agent(
            project_id, agent_slug, display_name=display_name, request_options=request_options
        )
        return _response.data

    async def create_definition_revision(
        self,
        project_id: str,
        agent_slug: str,
        *,
        content_digest: str,
        definition: AgentDefinition,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DefinitionRevisionResult:
        """
        Stage a changed definition as a draft revision; the live definition is a no-op.

        Parameters
        ----------
        project_id : str

        agent_slug : str

        content_digest : str

        definition : AgentDefinition

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DefinitionRevisionResult
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AgentDefinition, AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.managed_agents.create_definition_revision(
                project_id="project_id",
                agent_slug="agent_slug",
                content_digest="contentDigest",
                definition=AgentDefinition(
                    schema="sikaru.agent.contract.v1",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_definition_revision(
            project_id,
            agent_slug,
            content_digest=content_digest,
            definition=definition,
            request_options=request_options,
        )
        return _response.data

    async def get_definition_revision(
        self,
        project_id: str,
        agent_slug: str,
        changeset_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DefinitionRevisionView:
        """
        Parameters
        ----------
        project_id : str

        agent_slug : str

        changeset_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DefinitionRevisionView
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.managed_agents.get_definition_revision(
                project_id="project_id",
                agent_slug="agent_slug",
                changeset_id="changeset_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_definition_revision(
            project_id, agent_slug, changeset_id, request_options=request_options
        )
        return _response.data
