# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.authorization import Authorization
from ..types.availability import Availability
from ..types.binding import Binding
from ..types.channel_identity_app import ChannelIdentityApp
from ..types.channel_identity_app_id import ChannelIdentityAppId
from ..types.channel_identity_app_ur_ls import ChannelIdentityAppUrLs
from ..types.creation_resume import CreationResume
from ..types.creation_resume_id import CreationResumeId
from ..types.delivery import Delivery
from ..types.dm_challenge import DmChallenge
from ..types.dm_status import DmStatus
from ..types.http_credential import HttpCredential
from ..types.installation import Installation
from ..types.o_auth_result import OAuthResult
from ..types.personal_access_configuration import PersonalAccessConfiguration
from ..types.personal_slack_challenge import PersonalSlackChallenge
from ..types.personal_slack_status import PersonalSlackStatus
from ..types.receipt_summary import ReceiptSummary
from ..types.room import Room
from .raw_client import AsyncRawChannelsClient, RawChannelsClient
from .types.binding_status_status import BindingStatusStatus
from .types.create_binding_destination_kind import CreateBindingDestinationKind
from .types.create_binding_transport import CreateBindingTransport

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ChannelsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawChannelsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawChannelsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawChannelsClient
        """
        return self._raw_client

    def availability(self, project_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Availability:
        """
        Parameters
        ----------
        project_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Availability
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.channels.availability(
            project_id="project_id",
        )
        """
        _response = self._raw_client.availability(project_id, request_options=request_options)
        return _response.data

    def bindings(
        self, project_id: str, *, agent_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[Binding]:
        """
        Parameters
        ----------
        project_id : str

        agent_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[Binding]
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.channels.bindings(
            project_id="project_id",
            agent_id="agent_id",
        )
        """
        _response = self._raw_client.bindings(project_id, agent_id=agent_id, request_options=request_options)
        return _response.data

    def create_binding(
        self,
        project_id: str,
        *,
        agent_id: str,
        transport: CreateBindingTransport,
        destination_id: typing.Optional[str] = OMIT,
        destination_kind: typing.Optional[CreateBindingDestinationKind] = OMIT,
        installation_id: typing.Optional[str] = OMIT,
        recipient_id: typing.Optional[str] = OMIT,
        verification_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Binding:
        """
        Parameters
        ----------
        project_id : str

        agent_id : str

        transport : CreateBindingTransport

        destination_id : typing.Optional[str]

        destination_kind : typing.Optional[CreateBindingDestinationKind]

        installation_id : typing.Optional[str]

        recipient_id : typing.Optional[str]

        verification_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Binding
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.channels.create_binding(
            project_id="project_id",
            agent_id="agent_id",
            transport="http",
        )
        """
        _response = self._raw_client.create_binding(
            project_id,
            agent_id=agent_id,
            transport=transport,
            destination_id=destination_id,
            destination_kind=destination_kind,
            installation_id=installation_id,
            recipient_id=recipient_id,
            verification_id=verification_id,
            request_options=request_options,
        )
        return _response.data

    def delete_http_binding(
        self, project_id: str, binding_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        project_id : str

        binding_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.channels.delete_http_binding(
            project_id="project_id",
            binding_id="binding_id",
        )
        """
        _response = self._raw_client.delete_http_binding(project_id, binding_id, request_options=request_options)
        return _response.data

    def status(
        self,
        project_id: str,
        binding_id: str,
        *,
        status: BindingStatusStatus,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Binding:
        """
        Parameters
        ----------
        project_id : str

        binding_id : str

        status : BindingStatusStatus

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Binding
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.channels.status(
            project_id="project_id",
            binding_id="binding_id",
            status="active",
        )
        """
        _response = self._raw_client.status(project_id, binding_id, status=status, request_options=request_options)
        return _response.data

    def configure_http_binding(
        self,
        project_id: str,
        binding_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        pending_cap: typing.Optional[int] = OMIT,
        per_minute: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Binding:
        """
        Parameters
        ----------
        project_id : str

        binding_id : str

        name : typing.Optional[str]

        pending_cap : typing.Optional[int]

        per_minute : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Binding
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.channels.configure_http_binding(
            project_id="project_id",
            binding_id="binding_id",
        )
        """
        _response = self._raw_client.configure_http_binding(
            project_id,
            binding_id,
            name=name,
            pending_cap=pending_cap,
            per_minute=per_minute,
            request_options=request_options,
        )
        return _response.data

    def issue_http_credential(
        self, project_id: str, binding_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpCredential:
        """
        Parameters
        ----------
        project_id : str

        binding_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpCredential
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.channels.issue_http_credential(
            project_id="project_id",
            binding_id="binding_id",
        )
        """
        _response = self._raw_client.issue_http_credential(project_id, binding_id, request_options=request_options)
        return _response.data

    def configure_personal_access(
        self,
        project_id: str,
        binding_id: str,
        *,
        enabled: bool,
        identity_app_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        shared_tenant_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PersonalAccessConfiguration:
        """
        Parameters
        ----------
        project_id : str

        binding_id : str

        enabled : bool

        identity_app_ids : typing.Optional[typing.Sequence[str]]

        shared_tenant_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PersonalAccessConfiguration
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.channels.configure_personal_access(
            project_id="project_id",
            binding_id="binding_id",
            enabled=True,
        )
        """
        _response = self._raw_client.configure_personal_access(
            project_id,
            binding_id,
            enabled=enabled,
            identity_app_ids=identity_app_ids,
            shared_tenant_id=shared_tenant_id,
            request_options=request_options,
        )
        return _response.data

    def recent_receipts(
        self, project_id: str, binding_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[ReceiptSummary]:
        """
        Parameters
        ----------
        project_id : str

        binding_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ReceiptSummary]
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.channels.recent_receipts(
            project_id="project_id",
            binding_id="binding_id",
        )
        """
        _response = self._raw_client.recent_receipts(project_id, binding_id, request_options=request_options)
        return _response.data

    def get_member_slack_link(
        self,
        project_id: str,
        binding_id: str,
        verification_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PersonalSlackStatus:
        """
        Parameters
        ----------
        project_id : str

        binding_id : str

        verification_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PersonalSlackStatus
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.channels.get_member_slack_link(
            project_id="project_id",
            binding_id="binding_id",
            verification_id="verification_id",
        )
        """
        _response = self._raw_client.get_member_slack_link(
            project_id, binding_id, verification_id, request_options=request_options
        )
        return _response.data

    def start_member_slack_link(
        self,
        project_id: str,
        binding_id: str,
        *,
        installation_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PersonalSlackChallenge:
        """
        Parameters
        ----------
        project_id : str

        binding_id : str

        installation_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PersonalSlackChallenge
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.channels.start_member_slack_link(
            project_id="project_id",
            binding_id="binding_id",
            installation_id="installation_id",
        )
        """
        _response = self._raw_client.start_member_slack_link(
            project_id, binding_id, installation_id=installation_id, request_options=request_options
        )
        return _response.data

    def unlink_member_slack_identity(
        self,
        project_id: str,
        binding_id: str,
        installation_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Parameters
        ----------
        project_id : str

        binding_id : str

        installation_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.channels.unlink_member_slack_identity(
            project_id="project_id",
            binding_id="binding_id",
            installation_id="installation_id",
        )
        """
        _response = self._raw_client.unlink_member_slack_identity(
            project_id, binding_id, installation_id, request_options=request_options
        )
        return _response.data

    def save_creation_resume(
        self,
        project_id: str,
        *,
        payload: typing.Dict[str, typing.Any],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreationResumeId:
        """
        Parameters
        ----------
        project_id : str

        payload : typing.Dict[str, typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreationResumeId
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.channels.save_creation_resume(
            project_id="project_id",
            payload={"key": "value"},
        )
        """
        _response = self._raw_client.save_creation_resume(project_id, payload=payload, request_options=request_options)
        return _response.data

    def get_creation_resume(
        self, project_id: str, resume_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CreationResume:
        """
        Parameters
        ----------
        project_id : str

        resume_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreationResume
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.channels.get_creation_resume(
            project_id="project_id",
            resume_id="resume_id",
        )
        """
        _response = self._raw_client.get_creation_resume(project_id, resume_id, request_options=request_options)
        return _response.data

    def list_identity_apps(
        self, project_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[ChannelIdentityApp]:
        """
        Parameters
        ----------
        project_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ChannelIdentityApp]
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.channels.list_identity_apps(
            project_id="project_id",
        )
        """
        _response = self._raw_client.list_identity_apps(project_id, request_options=request_options)
        return _response.data

    def create_identity_app(
        self,
        project_id: str,
        *,
        audience: str,
        issuer: str,
        public_jwk: typing.Dict[str, typing.Any],
        connection_callback_url: typing.Optional[str] = OMIT,
        private_channel_url: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ChannelIdentityAppId:
        """
        Parameters
        ----------
        project_id : str

        audience : str

        issuer : str

        public_jwk : typing.Dict[str, typing.Any]

        connection_callback_url : typing.Optional[str]

        private_channel_url : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ChannelIdentityAppId
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.channels.create_identity_app(
            project_id="project_id",
            audience="audience",
            issuer="issuer",
            public_jwk={"key": "value"},
        )
        """
        _response = self._raw_client.create_identity_app(
            project_id,
            audience=audience,
            issuer=issuer,
            public_jwk=public_jwk,
            connection_callback_url=connection_callback_url,
            private_channel_url=private_channel_url,
            request_options=request_options,
        )
        return _response.data

    def revoke_identity_app(
        self, project_id: str, app_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        project_id : str

        app_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.channels.revoke_identity_app(
            project_id="project_id",
            app_id="app_id",
        )
        """
        _response = self._raw_client.revoke_identity_app(project_id, app_id, request_options=request_options)
        return _response.data

    def update_identity_app_urls(
        self,
        project_id: str,
        app_id: str,
        *,
        connection_callback_url: typing.Optional[str] = OMIT,
        private_channel_url: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ChannelIdentityAppUrLs:
        """
        Parameters
        ----------
        project_id : str

        app_id : str

        connection_callback_url : typing.Optional[str]

        private_channel_url : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ChannelIdentityAppUrLs
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.channels.update_identity_app_urls(
            project_id="project_id",
            app_id="app_id",
        )
        """
        _response = self._raw_client.update_identity_app_urls(
            project_id,
            app_id,
            connection_callback_url=connection_callback_url,
            private_channel_url=private_channel_url,
            request_options=request_options,
        )
        return _response.data

    def revoke_subject(
        self,
        project_id: str,
        app_id: str,
        *,
        subject: str,
        tenant_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Parameters
        ----------
        project_id : str

        app_id : str

        subject : str

        tenant_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.channels.revoke_subject(
            project_id="project_id",
            app_id="app_id",
            subject="subject",
            tenant_id="tenant_id",
        )
        """
        _response = self._raw_client.revoke_subject(
            project_id, app_id, subject=subject, tenant_id=tenant_id, request_options=request_options
        )
        return _response.data

    def create_personal_slack_binding(
        self,
        project_id: str,
        *,
        agent_id: str,
        identity_app_id: str,
        installation_id: str,
        verification_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Binding:
        """
        Parameters
        ----------
        project_id : str

        agent_id : str

        identity_app_id : str

        installation_id : str

        verification_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Binding
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.channels.create_personal_slack_binding(
            project_id="project_id",
            agent_id="agent_id",
            identity_app_id="identity_app_id",
            installation_id="installation_id",
            verification_id="verification_id",
        )
        """
        _response = self._raw_client.create_personal_slack_binding(
            project_id,
            agent_id=agent_id,
            identity_app_id=identity_app_id,
            installation_id=installation_id,
            verification_id=verification_id,
            request_options=request_options,
        )
        return _response.data

    def delivery(
        self, project_id: str, run_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[Delivery]:
        """
        Parameters
        ----------
        project_id : str

        run_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[Delivery]
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.channels.delivery(
            project_id="project_id",
            run_id="run_id",
        )
        """
        _response = self._raw_client.delivery(project_id, run_id, request_options=request_options)
        return _response.data

    def resend_delivery(
        self,
        project_id: str,
        run_id: str,
        *,
        acknowledge_possible_duplicate: bool,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Delivery:
        """
        Parameters
        ----------
        project_id : str

        run_id : str

        acknowledge_possible_duplicate : bool

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Delivery
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.channels.resend_delivery(
            project_id="project_id",
            run_id="run_id",
            acknowledge_possible_duplicate=True,
        )
        """
        _response = self._raw_client.resend_delivery(
            project_id,
            run_id,
            acknowledge_possible_duplicate=acknowledge_possible_duplicate,
            request_options=request_options,
        )
        return _response.data

    def dm_status(
        self, project_id: str, verification_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DmStatus:
        """
        Parameters
        ----------
        project_id : str

        verification_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DmStatus
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.channels.dm_status(
            project_id="project_id",
            verification_id="verification_id",
        )
        """
        _response = self._raw_client.dm_status(project_id, verification_id, request_options=request_options)
        return _response.data

    def installations(
        self, project_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[Installation]:
        """
        Parameters
        ----------
        project_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[Installation]
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.channels.installations(
            project_id="project_id",
        )
        """
        _response = self._raw_client.installations(project_id, request_options=request_options)
        return _response.data

    def disconnect(
        self, project_id: str, installation_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> Installation:
        """
        Parameters
        ----------
        project_id : str

        installation_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Installation
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.channels.disconnect(
            project_id="project_id",
            installation_id="installation_id",
        )
        """
        _response = self._raw_client.disconnect(project_id, installation_id, request_options=request_options)
        return _response.data

    def start_dm(
        self, project_id: str, installation_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DmChallenge:
        """
        Parameters
        ----------
        project_id : str

        installation_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DmChallenge
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.channels.start_dm(
            project_id="project_id",
            installation_id="installation_id",
        )
        """
        _response = self._raw_client.start_dm(project_id, installation_id, request_options=request_options)
        return _response.data

    def rooms(
        self, project_id: str, installation_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[Room]:
        """
        Parameters
        ----------
        project_id : str

        installation_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[Room]
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.channels.rooms(
            project_id="project_id",
            installation_id="installation_id",
        )
        """
        _response = self._raw_client.rooms(project_id, installation_id, request_options=request_options)
        return _response.data

    def complete(
        self,
        project_id: str,
        *,
        state: str,
        code: typing.Optional[str] = OMIT,
        error: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OAuthResult:
        """
        Parameters
        ----------
        project_id : str

        state : str

        code : typing.Optional[str]

        error : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OAuthResult
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.channels.complete(
            project_id="project_id",
            state="state",
        )
        """
        _response = self._raw_client.complete(
            project_id, state=state, code=code, error=error, request_options=request_options
        )
        return _response.data

    def start(
        self,
        project_id: str,
        *,
        installation_id: typing.Optional[str] = OMIT,
        resume_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Authorization:
        """
        Parameters
        ----------
        project_id : str

        installation_id : typing.Optional[str]

        resume_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Authorization
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.channels.start(
            project_id="project_id",
        )
        """
        _response = self._raw_client.start(
            project_id, installation_id=installation_id, resume_id=resume_id, request_options=request_options
        )
        return _response.data


class AsyncChannelsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawChannelsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawChannelsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawChannelsClient
        """
        return self._raw_client

    async def availability(
        self, project_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> Availability:
        """
        Parameters
        ----------
        project_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Availability
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channels.availability(
                project_id="project_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.availability(project_id, request_options=request_options)
        return _response.data

    async def bindings(
        self, project_id: str, *, agent_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[Binding]:
        """
        Parameters
        ----------
        project_id : str

        agent_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[Binding]
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channels.bindings(
                project_id="project_id",
                agent_id="agent_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.bindings(project_id, agent_id=agent_id, request_options=request_options)
        return _response.data

    async def create_binding(
        self,
        project_id: str,
        *,
        agent_id: str,
        transport: CreateBindingTransport,
        destination_id: typing.Optional[str] = OMIT,
        destination_kind: typing.Optional[CreateBindingDestinationKind] = OMIT,
        installation_id: typing.Optional[str] = OMIT,
        recipient_id: typing.Optional[str] = OMIT,
        verification_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Binding:
        """
        Parameters
        ----------
        project_id : str

        agent_id : str

        transport : CreateBindingTransport

        destination_id : typing.Optional[str]

        destination_kind : typing.Optional[CreateBindingDestinationKind]

        installation_id : typing.Optional[str]

        recipient_id : typing.Optional[str]

        verification_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Binding
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channels.create_binding(
                project_id="project_id",
                agent_id="agent_id",
                transport="http",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_binding(
            project_id,
            agent_id=agent_id,
            transport=transport,
            destination_id=destination_id,
            destination_kind=destination_kind,
            installation_id=installation_id,
            recipient_id=recipient_id,
            verification_id=verification_id,
            request_options=request_options,
        )
        return _response.data

    async def delete_http_binding(
        self, project_id: str, binding_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        project_id : str

        binding_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channels.delete_http_binding(
                project_id="project_id",
                binding_id="binding_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_http_binding(project_id, binding_id, request_options=request_options)
        return _response.data

    async def status(
        self,
        project_id: str,
        binding_id: str,
        *,
        status: BindingStatusStatus,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Binding:
        """
        Parameters
        ----------
        project_id : str

        binding_id : str

        status : BindingStatusStatus

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Binding
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channels.status(
                project_id="project_id",
                binding_id="binding_id",
                status="active",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.status(
            project_id, binding_id, status=status, request_options=request_options
        )
        return _response.data

    async def configure_http_binding(
        self,
        project_id: str,
        binding_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        pending_cap: typing.Optional[int] = OMIT,
        per_minute: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Binding:
        """
        Parameters
        ----------
        project_id : str

        binding_id : str

        name : typing.Optional[str]

        pending_cap : typing.Optional[int]

        per_minute : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Binding
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channels.configure_http_binding(
                project_id="project_id",
                binding_id="binding_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.configure_http_binding(
            project_id,
            binding_id,
            name=name,
            pending_cap=pending_cap,
            per_minute=per_minute,
            request_options=request_options,
        )
        return _response.data

    async def issue_http_credential(
        self, project_id: str, binding_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpCredential:
        """
        Parameters
        ----------
        project_id : str

        binding_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpCredential
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channels.issue_http_credential(
                project_id="project_id",
                binding_id="binding_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.issue_http_credential(
            project_id, binding_id, request_options=request_options
        )
        return _response.data

    async def configure_personal_access(
        self,
        project_id: str,
        binding_id: str,
        *,
        enabled: bool,
        identity_app_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        shared_tenant_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PersonalAccessConfiguration:
        """
        Parameters
        ----------
        project_id : str

        binding_id : str

        enabled : bool

        identity_app_ids : typing.Optional[typing.Sequence[str]]

        shared_tenant_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PersonalAccessConfiguration
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channels.configure_personal_access(
                project_id="project_id",
                binding_id="binding_id",
                enabled=True,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.configure_personal_access(
            project_id,
            binding_id,
            enabled=enabled,
            identity_app_ids=identity_app_ids,
            shared_tenant_id=shared_tenant_id,
            request_options=request_options,
        )
        return _response.data

    async def recent_receipts(
        self, project_id: str, binding_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[ReceiptSummary]:
        """
        Parameters
        ----------
        project_id : str

        binding_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ReceiptSummary]
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channels.recent_receipts(
                project_id="project_id",
                binding_id="binding_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.recent_receipts(project_id, binding_id, request_options=request_options)
        return _response.data

    async def get_member_slack_link(
        self,
        project_id: str,
        binding_id: str,
        verification_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PersonalSlackStatus:
        """
        Parameters
        ----------
        project_id : str

        binding_id : str

        verification_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PersonalSlackStatus
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channels.get_member_slack_link(
                project_id="project_id",
                binding_id="binding_id",
                verification_id="verification_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_member_slack_link(
            project_id, binding_id, verification_id, request_options=request_options
        )
        return _response.data

    async def start_member_slack_link(
        self,
        project_id: str,
        binding_id: str,
        *,
        installation_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PersonalSlackChallenge:
        """
        Parameters
        ----------
        project_id : str

        binding_id : str

        installation_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PersonalSlackChallenge
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channels.start_member_slack_link(
                project_id="project_id",
                binding_id="binding_id",
                installation_id="installation_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.start_member_slack_link(
            project_id, binding_id, installation_id=installation_id, request_options=request_options
        )
        return _response.data

    async def unlink_member_slack_identity(
        self,
        project_id: str,
        binding_id: str,
        installation_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Parameters
        ----------
        project_id : str

        binding_id : str

        installation_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channels.unlink_member_slack_identity(
                project_id="project_id",
                binding_id="binding_id",
                installation_id="installation_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.unlink_member_slack_identity(
            project_id, binding_id, installation_id, request_options=request_options
        )
        return _response.data

    async def save_creation_resume(
        self,
        project_id: str,
        *,
        payload: typing.Dict[str, typing.Any],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreationResumeId:
        """
        Parameters
        ----------
        project_id : str

        payload : typing.Dict[str, typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreationResumeId
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channels.save_creation_resume(
                project_id="project_id",
                payload={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.save_creation_resume(
            project_id, payload=payload, request_options=request_options
        )
        return _response.data

    async def get_creation_resume(
        self, project_id: str, resume_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CreationResume:
        """
        Parameters
        ----------
        project_id : str

        resume_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreationResume
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channels.get_creation_resume(
                project_id="project_id",
                resume_id="resume_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_creation_resume(project_id, resume_id, request_options=request_options)
        return _response.data

    async def list_identity_apps(
        self, project_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[ChannelIdentityApp]:
        """
        Parameters
        ----------
        project_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ChannelIdentityApp]
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channels.list_identity_apps(
                project_id="project_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_identity_apps(project_id, request_options=request_options)
        return _response.data

    async def create_identity_app(
        self,
        project_id: str,
        *,
        audience: str,
        issuer: str,
        public_jwk: typing.Dict[str, typing.Any],
        connection_callback_url: typing.Optional[str] = OMIT,
        private_channel_url: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ChannelIdentityAppId:
        """
        Parameters
        ----------
        project_id : str

        audience : str

        issuer : str

        public_jwk : typing.Dict[str, typing.Any]

        connection_callback_url : typing.Optional[str]

        private_channel_url : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ChannelIdentityAppId
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channels.create_identity_app(
                project_id="project_id",
                audience="audience",
                issuer="issuer",
                public_jwk={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_identity_app(
            project_id,
            audience=audience,
            issuer=issuer,
            public_jwk=public_jwk,
            connection_callback_url=connection_callback_url,
            private_channel_url=private_channel_url,
            request_options=request_options,
        )
        return _response.data

    async def revoke_identity_app(
        self, project_id: str, app_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        project_id : str

        app_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channels.revoke_identity_app(
                project_id="project_id",
                app_id="app_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.revoke_identity_app(project_id, app_id, request_options=request_options)
        return _response.data

    async def update_identity_app_urls(
        self,
        project_id: str,
        app_id: str,
        *,
        connection_callback_url: typing.Optional[str] = OMIT,
        private_channel_url: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ChannelIdentityAppUrLs:
        """
        Parameters
        ----------
        project_id : str

        app_id : str

        connection_callback_url : typing.Optional[str]

        private_channel_url : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ChannelIdentityAppUrLs
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channels.update_identity_app_urls(
                project_id="project_id",
                app_id="app_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_identity_app_urls(
            project_id,
            app_id,
            connection_callback_url=connection_callback_url,
            private_channel_url=private_channel_url,
            request_options=request_options,
        )
        return _response.data

    async def revoke_subject(
        self,
        project_id: str,
        app_id: str,
        *,
        subject: str,
        tenant_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Parameters
        ----------
        project_id : str

        app_id : str

        subject : str

        tenant_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channels.revoke_subject(
                project_id="project_id",
                app_id="app_id",
                subject="subject",
                tenant_id="tenant_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.revoke_subject(
            project_id, app_id, subject=subject, tenant_id=tenant_id, request_options=request_options
        )
        return _response.data

    async def create_personal_slack_binding(
        self,
        project_id: str,
        *,
        agent_id: str,
        identity_app_id: str,
        installation_id: str,
        verification_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Binding:
        """
        Parameters
        ----------
        project_id : str

        agent_id : str

        identity_app_id : str

        installation_id : str

        verification_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Binding
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channels.create_personal_slack_binding(
                project_id="project_id",
                agent_id="agent_id",
                identity_app_id="identity_app_id",
                installation_id="installation_id",
                verification_id="verification_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_personal_slack_binding(
            project_id,
            agent_id=agent_id,
            identity_app_id=identity_app_id,
            installation_id=installation_id,
            verification_id=verification_id,
            request_options=request_options,
        )
        return _response.data

    async def delivery(
        self, project_id: str, run_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[Delivery]:
        """
        Parameters
        ----------
        project_id : str

        run_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[Delivery]
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channels.delivery(
                project_id="project_id",
                run_id="run_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delivery(project_id, run_id, request_options=request_options)
        return _response.data

    async def resend_delivery(
        self,
        project_id: str,
        run_id: str,
        *,
        acknowledge_possible_duplicate: bool,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Delivery:
        """
        Parameters
        ----------
        project_id : str

        run_id : str

        acknowledge_possible_duplicate : bool

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Delivery
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channels.resend_delivery(
                project_id="project_id",
                run_id="run_id",
                acknowledge_possible_duplicate=True,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.resend_delivery(
            project_id,
            run_id,
            acknowledge_possible_duplicate=acknowledge_possible_duplicate,
            request_options=request_options,
        )
        return _response.data

    async def dm_status(
        self, project_id: str, verification_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DmStatus:
        """
        Parameters
        ----------
        project_id : str

        verification_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DmStatus
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channels.dm_status(
                project_id="project_id",
                verification_id="verification_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.dm_status(project_id, verification_id, request_options=request_options)
        return _response.data

    async def installations(
        self, project_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[Installation]:
        """
        Parameters
        ----------
        project_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[Installation]
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channels.installations(
                project_id="project_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.installations(project_id, request_options=request_options)
        return _response.data

    async def disconnect(
        self, project_id: str, installation_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> Installation:
        """
        Parameters
        ----------
        project_id : str

        installation_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Installation
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channels.disconnect(
                project_id="project_id",
                installation_id="installation_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.disconnect(project_id, installation_id, request_options=request_options)
        return _response.data

    async def start_dm(
        self, project_id: str, installation_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DmChallenge:
        """
        Parameters
        ----------
        project_id : str

        installation_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DmChallenge
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channels.start_dm(
                project_id="project_id",
                installation_id="installation_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.start_dm(project_id, installation_id, request_options=request_options)
        return _response.data

    async def rooms(
        self, project_id: str, installation_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[Room]:
        """
        Parameters
        ----------
        project_id : str

        installation_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[Room]
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channels.rooms(
                project_id="project_id",
                installation_id="installation_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.rooms(project_id, installation_id, request_options=request_options)
        return _response.data

    async def complete(
        self,
        project_id: str,
        *,
        state: str,
        code: typing.Optional[str] = OMIT,
        error: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OAuthResult:
        """
        Parameters
        ----------
        project_id : str

        state : str

        code : typing.Optional[str]

        error : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OAuthResult
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channels.complete(
                project_id="project_id",
                state="state",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.complete(
            project_id, state=state, code=code, error=error, request_options=request_options
        )
        return _response.data

    async def start(
        self,
        project_id: str,
        *,
        installation_id: typing.Optional[str] = OMIT,
        resume_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Authorization:
        """
        Parameters
        ----------
        project_id : str

        installation_id : typing.Optional[str]

        resume_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Authorization
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.channels.start(
                project_id="project_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.start(
            project_id, installation_id=installation_id, resume_id=resume_id, request_options=request_options
        )
        return _response.data
