// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         description: "description"
 *     }
 */
export interface CreateProductWorkflowIntentRequest {
    description: string;
}
