// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         kind: "thumbs_up",
 *         target: "trace",
 *         targetId: "targetId"
 *     }
 */
export interface CreateFeedbackRequest {
    issueId?: string | null;
    kind: CreateFeedbackRequest.Kind;
    note?: string | null;
    sessionId?: string | null;
    spanId?: string | null;
    tag?: string | null;
    target: CreateFeedbackRequest.Target;
    targetId: string;
    traceId?: string | null;
}

export namespace CreateFeedbackRequest {
    export const Kind = {
            ThumbsUp: "thumbs_up",
            ThumbsDown: "thumbs_down",
            Annotation: "annotation"
        } as const;
    export type Kind = typeof Kind[keyof typeof Kind];
    export const Target = {
            Trace: "trace",
            Span: "span",
            Session: "session",
            Issue: "issue"
        } as const;
    export type Target = typeof Target[keyof typeof Target];
}
