// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         tenant_id: "tenant_id",
 *         user_id: "user_id"
 *     }
 */
export interface SessionInput {
    /** Automatically request evaluated harness improvements after completed turns. Requires harness:write and configured improvement policy. */
    auto_improve?: boolean;
    conversation_id?: string | null;
    /** Draft sessions test the pinned agent definition without activation. Creating or appending draft sessions also requires harness:write. */
    environment?: SessionInput.Environment;
    final_output_schema?: Record<string, unknown> | null;
    idempotency_key?: string | null;
    reasoning_effort?: SessionInput.ReasoningEffort | null;
    tenant_id: string;
    user_id: string;
}

export namespace SessionInput {
    /** Draft sessions test the pinned agent definition without activation. Creating or appending draft sessions also requires harness:write. */
    export const Environment = {
            Production: "production",
            Draft: "draft"
        } as const;
    export type Environment = typeof Environment[keyof typeof Environment];
    export const ReasoningEffort = {
            None: "none",
            Minimal: "minimal",
            Low: "low",
            Medium: "medium",
            High: "high",
            Xhigh: "xhigh"
        } as const;
    export type ReasoningEffort = typeof ReasoningEffort[keyof typeof ReasoningEffort];
}
