// Code generated by Fern. DO NOT EDIT.

package connections

import (
	context "context"
	os "os"

	_go "github.com/aadi-labs/sikaru-sdk/go"
	core "github.com/aadi-labs/sikaru-sdk/go/core"
	internal "github.com/aadi-labs/sikaru-sdk/go/internal"
	option "github.com/aadi-labs/sikaru-sdk/go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.APIKey == "" {
		options.APIKey = os.Getenv("SIKARU_API_KEY")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Example:
//
//	client.Connections.ListConnections(
//	    context.TODO(),
//	    "project_id",
//	)
func (c *Client) ListConnections(
	ctx context.Context,
	projectID string,
	opts ...option.RequestOption,
) ([]*_go.Connection, error) {
	response, err := c.WithRawResponse.ListConnections(
		ctx,
		projectID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &_go.CreateConnection{
//	    Config: &_go.ConnectionConfig{},
//	    DisplayName: "display_name",
//	    Kind: _go.CreateConnectionKindMcp,
//	}
//	client.Connections.CreateConnection(
//	    context.TODO(),
//	    "project_id",
//	    request,
//	)
func (c *Client) CreateConnection(
	ctx context.Context,
	projectID string,
	request *_go.CreateConnection,
	opts ...option.RequestOption,
) (*_go.Connection, error) {
	response, err := c.WithRawResponse.CreateConnection(
		ctx,
		projectID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	client.Connections.GetConnection(
//	    context.TODO(),
//	    "project_id",
//	    "connection_id",
//	)
func (c *Client) GetConnection(
	ctx context.Context,
	projectID string,
	connectionID string,
	opts ...option.RequestOption,
) (*_go.Connection, error) {
	response, err := c.WithRawResponse.GetConnection(
		ctx,
		projectID,
		connectionID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	client.Connections.Authorize(
//	    context.TODO(),
//	    "project_id",
//	    "connection_id",
//	)
func (c *Client) Authorize(
	ctx context.Context,
	projectID string,
	connectionID string,
	opts ...option.RequestOption,
) (*_go.ConnectionAuthorization, error) {
	response, err := c.WithRawResponse.Authorize(
		ctx,
		projectID,
		connectionID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &_go.CompleteAuthorization{
//	    State: "state",
//	}
//	client.Connections.Complete(
//	    context.TODO(),
//	    "project_id",
//	    "connection_id",
//	    request,
//	)
func (c *Client) Complete(
	ctx context.Context,
	projectID string,
	connectionID string,
	request *_go.CompleteAuthorization,
	opts ...option.RequestOption,
) (*_go.Connection, error) {
	response, err := c.WithRawResponse.Complete(
		ctx,
		projectID,
		connectionID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &_go.ReplaceCredentials{
//	    Credentials: &_go.ConnectionCredentials{},
//	}
//	client.Connections.Credentials(
//	    context.TODO(),
//	    "project_id",
//	    "connection_id",
//	    request,
//	)
func (c *Client) Credentials(
	ctx context.Context,
	projectID string,
	connectionID string,
	request *_go.ReplaceCredentials,
	opts ...option.RequestOption,
) (*_go.Connection, error) {
	response, err := c.WithRawResponse.Credentials(
		ctx,
		projectID,
		connectionID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	client.Connections.Disable(
//	    context.TODO(),
//	    "project_id",
//	    "connection_id",
//	)
func (c *Client) Disable(
	ctx context.Context,
	projectID string,
	connectionID string,
	opts ...option.RequestOption,
) (*_go.Connection, error) {
	response, err := c.WithRawResponse.Disable(
		ctx,
		projectID,
		connectionID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	client.Connections.Disconnect(
//	    context.TODO(),
//	    "project_id",
//	    "connection_id",
//	)
func (c *Client) Disconnect(
	ctx context.Context,
	projectID string,
	connectionID string,
	opts ...option.RequestOption,
) (*_go.Connection, error) {
	response, err := c.WithRawResponse.Disconnect(
		ctx,
		projectID,
		connectionID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	client.Connections.Discover(
//	    context.TODO(),
//	    "project_id",
//	    "connection_id",
//	)
func (c *Client) Discover(
	ctx context.Context,
	projectID string,
	connectionID string,
	opts ...option.RequestOption,
) (*_go.Connection, error) {
	response, err := c.WithRawResponse.Discover(
		ctx,
		projectID,
		connectionID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	client.Connections.Enable(
//	    context.TODO(),
//	    "project_id",
//	    "connection_id",
//	)
func (c *Client) Enable(
	ctx context.Context,
	projectID string,
	connectionID string,
	opts ...option.RequestOption,
) (*_go.Connection, error) {
	response, err := c.WithRawResponse.Enable(
		ctx,
		projectID,
		connectionID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	client.Connections.Events(
//	    context.TODO(),
//	    "project_id",
//	    "connection_id",
//	)
func (c *Client) Events(
	ctx context.Context,
	projectID string,
	connectionID string,
	opts ...option.RequestOption,
) ([]*_go.ConnectionEvent, error) {
	response, err := c.WithRawResponse.Events(
		ctx,
		projectID,
		connectionID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &_go.GrantConnection{
//	    AgentID: "agent_id",
//	    Tools: []string{
//	        "tools",
//	    },
//	}
//	client.Connections.Grant(
//	    context.TODO(),
//	    "project_id",
//	    "connection_id",
//	    request,
//	)
func (c *Client) Grant(
	ctx context.Context,
	projectID string,
	connectionID string,
	request *_go.GrantConnection,
	opts ...option.RequestOption,
) (*_go.Connection, error) {
	response, err := c.WithRawResponse.Grant(
		ctx,
		projectID,
		connectionID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	client.Connections.RevokeGrant(
//	    context.TODO(),
//	    "project_id",
//	    "connection_id",
//	    "grant_id",
//	)
func (c *Client) RevokeGrant(
	ctx context.Context,
	projectID string,
	connectionID string,
	grantID string,
	opts ...option.RequestOption,
) (*_go.Connection, error) {
	response, err := c.WithRawResponse.RevokeGrant(
		ctx,
		projectID,
		connectionID,
		grantID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
