// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         displayName: "displayName"
 *     }
 */
export interface RenameAgent {
    displayName: string;
}
