// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/aadi-labs/sikaru-sdk/go/internal"
	big "math/big"
)

var (
	pollComputeWorkersRequestFieldWaitSeconds = big.NewInt(1 << 0)
	pollComputeWorkersRequestFieldLimit       = big.NewInt(1 << 1)
)

type PollComputeWorkersRequest struct {
	WaitSeconds *int `json:"-" url:"wait_seconds,omitempty"`
	Limit       *int `json:"-" url:"limit,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PollComputeWorkersRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetWaitSeconds sets the WaitSeconds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PollComputeWorkersRequest) SetWaitSeconds(waitSeconds *int) {
	p.WaitSeconds = waitSeconds
	p.require(pollComputeWorkersRequestFieldWaitSeconds)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PollComputeWorkersRequest) SetLimit(limit *int) {
	p.Limit = limit
	p.require(pollComputeWorkersRequestFieldLimit)
}

var (
	queuePageFieldAttachments      = big.NewInt(1 << 0)
	queuePageFieldPollAfterSeconds = big.NewInt(1 << 1)
)

type QueuePage struct {
	Attachments      []*AttachmentView `json:"attachments" url:"attachments"`
	PollAfterSeconds *int              `json:"poll_after_seconds,omitempty" url:"poll_after_seconds,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (q *QueuePage) GetAttachments() []*AttachmentView {
	if q == nil {
		return nil
	}
	return q.Attachments
}

func (q *QueuePage) GetPollAfterSeconds() *int {
	if q == nil {
		return nil
	}
	return q.PollAfterSeconds
}

func (q *QueuePage) GetExtraProperties() map[string]interface{} {
	if q == nil {
		return nil
	}
	return q.extraProperties
}

func (q *QueuePage) require(field *big.Int) {
	if q.explicitFields == nil {
		q.explicitFields = big.NewInt(0)
	}
	q.explicitFields.Or(q.explicitFields, field)
}

// SetAttachments sets the Attachments field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueuePage) SetAttachments(attachments []*AttachmentView) {
	q.Attachments = attachments
	q.require(queuePageFieldAttachments)
}

// SetPollAfterSeconds sets the PollAfterSeconds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QueuePage) SetPollAfterSeconds(pollAfterSeconds *int) {
	q.PollAfterSeconds = pollAfterSeconds
	q.require(queuePageFieldPollAfterSeconds)
}

func (q *QueuePage) UnmarshalJSON(data []byte) error {
	type unmarshaler QueuePage
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*q = QueuePage(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *q)
	if err != nil {
		return err
	}
	q.extraProperties = extraProperties
	q.rawJSON = json.RawMessage(data)
	return nil
}

func (q *QueuePage) MarshalJSON() ([]byte, error) {
	type embed QueuePage
	var marshaler = struct {
		embed
	}{
		embed: embed(*q),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, q.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (q *QueuePage) String() string {
	if q == nil {
		return "<nil>"
	}
	if len(q.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(q.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(q); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", q)
}
