// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/aadi-labs/sikaru-sdk/go/internal"
	big "math/big"
)

var (
	completeAuthorizationFieldQuery = big.NewInt(1 << 0)
	completeAuthorizationFieldState = big.NewInt(1 << 1)
)

type CompleteAuthorization struct {
	Query map[string]string `json:"query,omitempty" url:"-"`
	State string            `json:"state" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CompleteAuthorization) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetQuery sets the Query field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CompleteAuthorization) SetQuery(query map[string]string) {
	c.Query = query
	c.require(completeAuthorizationFieldQuery)
}

// SetState sets the State field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CompleteAuthorization) SetState(state string) {
	c.State = state
	c.require(completeAuthorizationFieldState)
}

func (c *CompleteAuthorization) UnmarshalJSON(data []byte) error {
	type unmarshaler CompleteAuthorization
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CompleteAuthorization(body)
	return nil
}

func (c *CompleteAuthorization) MarshalJSON() ([]byte, error) {
	type embed CompleteAuthorization
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	createConnectionFieldConfig      = big.NewInt(1 << 0)
	createConnectionFieldCredentials = big.NewInt(1 << 1)
	createConnectionFieldDisplayName = big.NewInt(1 << 2)
	createConnectionFieldKind        = big.NewInt(1 << 3)
	createConnectionFieldOwnership   = big.NewInt(1 << 4)
)

type CreateConnection struct {
	Config      *ConnectionConfig          `json:"config" url:"-"`
	Credentials *ConnectionCredentials     `json:"credentials,omitempty" url:"-"`
	DisplayName string                     `json:"display_name" url:"-"`
	Kind        CreateConnectionKind       `json:"kind" url:"-"`
	Ownership   *CreateConnectionOwnership `json:"ownership,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateConnection) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetConfig sets the Config field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateConnection) SetConfig(config *ConnectionConfig) {
	c.Config = config
	c.require(createConnectionFieldConfig)
}

// SetCredentials sets the Credentials field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateConnection) SetCredentials(credentials *ConnectionCredentials) {
	c.Credentials = credentials
	c.require(createConnectionFieldCredentials)
}

// SetDisplayName sets the DisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateConnection) SetDisplayName(displayName string) {
	c.DisplayName = displayName
	c.require(createConnectionFieldDisplayName)
}

// SetKind sets the Kind field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateConnection) SetKind(kind CreateConnectionKind) {
	c.Kind = kind
	c.require(createConnectionFieldKind)
}

// SetOwnership sets the Ownership field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateConnection) SetOwnership(ownership *CreateConnectionOwnership) {
	c.Ownership = ownership
	c.require(createConnectionFieldOwnership)
}

func (c *CreateConnection) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateConnection
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateConnection(body)
	return nil
}

func (c *CreateConnection) MarshalJSON() ([]byte, error) {
	type embed CreateConnection
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	replaceCredentialsFieldCredentials = big.NewInt(1 << 0)
)

type ReplaceCredentials struct {
	Credentials *ConnectionCredentials `json:"credentials" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *ReplaceCredentials) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetCredentials sets the Credentials field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReplaceCredentials) SetCredentials(credentials *ConnectionCredentials) {
	r.Credentials = credentials
	r.require(replaceCredentialsFieldCredentials)
}

func (r *ReplaceCredentials) UnmarshalJSON(data []byte) error {
	type unmarshaler ReplaceCredentials
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*r = ReplaceCredentials(body)
	return nil
}

func (r *ReplaceCredentials) MarshalJSON() ([]byte, error) {
	type embed ReplaceCredentials
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	grantConnectionFieldAgentID     = big.NewInt(1 << 0)
	grantConnectionFieldApproval    = big.NewInt(1 << 1)
	grantConnectionFieldEnvironment = big.NewInt(1 << 2)
	grantConnectionFieldTools       = big.NewInt(1 << 3)
)

type GrantConnection struct {
	AgentID     string                      `json:"agent_id" url:"-"`
	Approval    *GrantConnectionApproval    `json:"approval,omitempty" url:"-"`
	Environment *GrantConnectionEnvironment `json:"environment,omitempty" url:"-"`
	Tools       []string                    `json:"tools" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GrantConnection) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetAgentID sets the AgentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrantConnection) SetAgentID(agentID string) {
	g.AgentID = agentID
	g.require(grantConnectionFieldAgentID)
}

// SetApproval sets the Approval field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrantConnection) SetApproval(approval *GrantConnectionApproval) {
	g.Approval = approval
	g.require(grantConnectionFieldApproval)
}

// SetEnvironment sets the Environment field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrantConnection) SetEnvironment(environment *GrantConnectionEnvironment) {
	g.Environment = environment
	g.require(grantConnectionFieldEnvironment)
}

// SetTools sets the Tools field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GrantConnection) SetTools(tools []string) {
	g.Tools = tools
	g.require(grantConnectionFieldTools)
}

func (g *GrantConnection) UnmarshalJSON(data []byte) error {
	type unmarshaler GrantConnection
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*g = GrantConnection(body)
	return nil
}

func (g *GrantConnection) MarshalJSON() ([]byte, error) {
	type embed GrantConnection
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	connectionFieldConfig      = big.NewInt(1 << 0)
	connectionFieldDisplayName = big.NewInt(1 << 1)
	connectionFieldExpiresAt   = big.NewInt(1 << 2)
	connectionFieldGrants      = big.NewInt(1 << 3)
	connectionFieldID          = big.NewInt(1 << 4)
	connectionFieldKind        = big.NewInt(1 << 5)
	connectionFieldOwner       = big.NewInt(1 << 6)
	connectionFieldOwnership   = big.NewInt(1 << 7)
	connectionFieldRevocation  = big.NewInt(1 << 8)
	connectionFieldStatus      = big.NewInt(1 << 9)
	connectionFieldTools       = big.NewInt(1 << 10)
	connectionFieldVersion     = big.NewInt(1 << 11)
)

type Connection struct {
	Config      *ConnectionConfig  `json:"config" url:"config"`
	DisplayName string             `json:"display_name" url:"display_name"`
	ExpiresAt   *float64           `json:"expires_at,omitempty" url:"expires_at,omitempty"`
	Grants      []*ConnectionGrant `json:"grants" url:"grants"`
	ID          string             `json:"id" url:"id"`
	Kind        string             `json:"kind" url:"kind"`
	Owner       string             `json:"owner" url:"owner"`
	Ownership   string             `json:"ownership" url:"ownership"`
	Revocation  string             `json:"revocation" url:"revocation"`
	Status      string             `json:"status" url:"status"`
	Tools       []*ConnectionTool  `json:"tools" url:"tools"`
	Version     int                `json:"version" url:"version"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *Connection) GetConfig() *ConnectionConfig {
	if c == nil {
		return nil
	}
	return c.Config
}

func (c *Connection) GetDisplayName() string {
	if c == nil {
		return ""
	}
	return c.DisplayName
}

func (c *Connection) GetExpiresAt() *float64 {
	if c == nil {
		return nil
	}
	return c.ExpiresAt
}

func (c *Connection) GetGrants() []*ConnectionGrant {
	if c == nil {
		return nil
	}
	return c.Grants
}

func (c *Connection) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *Connection) GetKind() string {
	if c == nil {
		return ""
	}
	return c.Kind
}

func (c *Connection) GetOwner() string {
	if c == nil {
		return ""
	}
	return c.Owner
}

func (c *Connection) GetOwnership() string {
	if c == nil {
		return ""
	}
	return c.Ownership
}

func (c *Connection) GetRevocation() string {
	if c == nil {
		return ""
	}
	return c.Revocation
}

func (c *Connection) GetStatus() string {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *Connection) GetTools() []*ConnectionTool {
	if c == nil {
		return nil
	}
	return c.Tools
}

func (c *Connection) GetVersion() int {
	if c == nil {
		return 0
	}
	return c.Version
}

func (c *Connection) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *Connection) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetConfig sets the Config field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Connection) SetConfig(config *ConnectionConfig) {
	c.Config = config
	c.require(connectionFieldConfig)
}

// SetDisplayName sets the DisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Connection) SetDisplayName(displayName string) {
	c.DisplayName = displayName
	c.require(connectionFieldDisplayName)
}

// SetExpiresAt sets the ExpiresAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Connection) SetExpiresAt(expiresAt *float64) {
	c.ExpiresAt = expiresAt
	c.require(connectionFieldExpiresAt)
}

// SetGrants sets the Grants field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Connection) SetGrants(grants []*ConnectionGrant) {
	c.Grants = grants
	c.require(connectionFieldGrants)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Connection) SetID(id string) {
	c.ID = id
	c.require(connectionFieldID)
}

// SetKind sets the Kind field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Connection) SetKind(kind string) {
	c.Kind = kind
	c.require(connectionFieldKind)
}

// SetOwner sets the Owner field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Connection) SetOwner(owner string) {
	c.Owner = owner
	c.require(connectionFieldOwner)
}

// SetOwnership sets the Ownership field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Connection) SetOwnership(ownership string) {
	c.Ownership = ownership
	c.require(connectionFieldOwnership)
}

// SetRevocation sets the Revocation field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Connection) SetRevocation(revocation string) {
	c.Revocation = revocation
	c.require(connectionFieldRevocation)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Connection) SetStatus(status string) {
	c.Status = status
	c.require(connectionFieldStatus)
}

// SetTools sets the Tools field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Connection) SetTools(tools []*ConnectionTool) {
	c.Tools = tools
	c.require(connectionFieldTools)
}

// SetVersion sets the Version field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Connection) SetVersion(version int) {
	c.Version = version
	c.require(connectionFieldVersion)
}

func (c *Connection) UnmarshalJSON(data []byte) error {
	type unmarshaler Connection
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = Connection(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *Connection) MarshalJSON() ([]byte, error) {
	type embed Connection
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *Connection) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	connectionAuthorizationFieldExpiresAt = big.NewInt(1 << 0)
	connectionAuthorizationFieldState     = big.NewInt(1 << 1)
	connectionAuthorizationFieldURL       = big.NewInt(1 << 2)
)

type ConnectionAuthorization struct {
	ExpiresAt float64 `json:"expires_at" url:"expires_at"`
	State     string  `json:"state" url:"state"`
	URL       string  `json:"url" url:"url"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ConnectionAuthorization) GetExpiresAt() float64 {
	if c == nil {
		return 0
	}
	return c.ExpiresAt
}

func (c *ConnectionAuthorization) GetState() string {
	if c == nil {
		return ""
	}
	return c.State
}

func (c *ConnectionAuthorization) GetURL() string {
	if c == nil {
		return ""
	}
	return c.URL
}

func (c *ConnectionAuthorization) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *ConnectionAuthorization) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetExpiresAt sets the ExpiresAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectionAuthorization) SetExpiresAt(expiresAt float64) {
	c.ExpiresAt = expiresAt
	c.require(connectionAuthorizationFieldExpiresAt)
}

// SetState sets the State field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectionAuthorization) SetState(state string) {
	c.State = state
	c.require(connectionAuthorizationFieldState)
}

// SetURL sets the URL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectionAuthorization) SetURL(url string) {
	c.URL = url
	c.require(connectionAuthorizationFieldURL)
}

func (c *ConnectionAuthorization) UnmarshalJSON(data []byte) error {
	type unmarshaler ConnectionAuthorization
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ConnectionAuthorization(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ConnectionAuthorization) MarshalJSON() ([]byte, error) {
	type embed ConnectionAuthorization
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ConnectionAuthorization) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	connectionConfigFieldAuth          = big.NewInt(1 << 0)
	connectionConfigFieldEndpoint      = big.NewInt(1 << 1)
	connectionConfigFieldHeaderName    = big.NewInt(1 << 2)
	connectionConfigFieldOauthClientID = big.NewInt(1 << 3)
	connectionConfigFieldOauthScopes   = big.NewInt(1 << 4)
	connectionConfigFieldToolkit       = big.NewInt(1 << 5)
)

type ConnectionConfig struct {
	Auth          *ConnectionConfigAuth `json:"auth,omitempty" url:"auth,omitempty"`
	Endpoint      *string               `json:"endpoint,omitempty" url:"endpoint,omitempty"`
	HeaderName    *string               `json:"header_name,omitempty" url:"header_name,omitempty"`
	OauthClientID *string               `json:"oauth_client_id,omitempty" url:"oauth_client_id,omitempty"`
	OauthScopes   []string              `json:"oauth_scopes,omitempty" url:"oauth_scopes,omitempty"`
	Toolkit       *string               `json:"toolkit,omitempty" url:"toolkit,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ConnectionConfig) GetAuth() *ConnectionConfigAuth {
	if c == nil {
		return nil
	}
	return c.Auth
}

func (c *ConnectionConfig) GetEndpoint() *string {
	if c == nil {
		return nil
	}
	return c.Endpoint
}

func (c *ConnectionConfig) GetHeaderName() *string {
	if c == nil {
		return nil
	}
	return c.HeaderName
}

func (c *ConnectionConfig) GetOauthClientID() *string {
	if c == nil {
		return nil
	}
	return c.OauthClientID
}

func (c *ConnectionConfig) GetOauthScopes() []string {
	if c == nil {
		return nil
	}
	return c.OauthScopes
}

func (c *ConnectionConfig) GetToolkit() *string {
	if c == nil {
		return nil
	}
	return c.Toolkit
}

func (c *ConnectionConfig) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *ConnectionConfig) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAuth sets the Auth field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectionConfig) SetAuth(auth *ConnectionConfigAuth) {
	c.Auth = auth
	c.require(connectionConfigFieldAuth)
}

// SetEndpoint sets the Endpoint field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectionConfig) SetEndpoint(endpoint *string) {
	c.Endpoint = endpoint
	c.require(connectionConfigFieldEndpoint)
}

// SetHeaderName sets the HeaderName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectionConfig) SetHeaderName(headerName *string) {
	c.HeaderName = headerName
	c.require(connectionConfigFieldHeaderName)
}

// SetOauthClientID sets the OauthClientID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectionConfig) SetOauthClientID(oauthClientID *string) {
	c.OauthClientID = oauthClientID
	c.require(connectionConfigFieldOauthClientID)
}

// SetOauthScopes sets the OauthScopes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectionConfig) SetOauthScopes(oauthScopes []string) {
	c.OauthScopes = oauthScopes
	c.require(connectionConfigFieldOauthScopes)
}

// SetToolkit sets the Toolkit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectionConfig) SetToolkit(toolkit *string) {
	c.Toolkit = toolkit
	c.require(connectionConfigFieldToolkit)
}

func (c *ConnectionConfig) UnmarshalJSON(data []byte) error {
	type unmarshaler ConnectionConfig
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ConnectionConfig(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ConnectionConfig) MarshalJSON() ([]byte, error) {
	type embed ConnectionConfig
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ConnectionConfig) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type ConnectionConfigAuth string

const (
	ConnectionConfigAuthNone   ConnectionConfigAuth = "none"
	ConnectionConfigAuthBearer ConnectionConfigAuth = "bearer"
	ConnectionConfigAuthAPIKey ConnectionConfigAuth = "api_key"
	ConnectionConfigAuthOauth  ConnectionConfigAuth = "oauth"
)

func NewConnectionConfigAuthFromString(s string) (ConnectionConfigAuth, error) {
	switch s {
	case "none":
		return ConnectionConfigAuthNone, nil
	case "bearer":
		return ConnectionConfigAuthBearer, nil
	case "api_key":
		return ConnectionConfigAuthAPIKey, nil
	case "oauth":
		return ConnectionConfigAuthOauth, nil
	}
	var t ConnectionConfigAuth
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c ConnectionConfigAuth) Ptr() *ConnectionConfigAuth {
	return &c
}

var (
	connectionCredentialsFieldOauthClientSecret = big.NewInt(1 << 0)
	connectionCredentialsFieldToken             = big.NewInt(1 << 1)
)

type ConnectionCredentials struct {
	OauthClientSecret *string `json:"oauth_client_secret,omitempty" url:"oauth_client_secret,omitempty"`
	Token             *string `json:"token,omitempty" url:"token,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ConnectionCredentials) GetOauthClientSecret() *string {
	if c == nil {
		return nil
	}
	return c.OauthClientSecret
}

func (c *ConnectionCredentials) GetToken() *string {
	if c == nil {
		return nil
	}
	return c.Token
}

func (c *ConnectionCredentials) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *ConnectionCredentials) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetOauthClientSecret sets the OauthClientSecret field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectionCredentials) SetOauthClientSecret(oauthClientSecret *string) {
	c.OauthClientSecret = oauthClientSecret
	c.require(connectionCredentialsFieldOauthClientSecret)
}

// SetToken sets the Token field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectionCredentials) SetToken(token *string) {
	c.Token = token
	c.require(connectionCredentialsFieldToken)
}

func (c *ConnectionCredentials) UnmarshalJSON(data []byte) error {
	type unmarshaler ConnectionCredentials
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ConnectionCredentials(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ConnectionCredentials) MarshalJSON() ([]byte, error) {
	type embed ConnectionCredentials
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ConnectionCredentials) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	connectionEventFieldAction    = big.NewInt(1 << 0)
	connectionEventFieldActor     = big.NewInt(1 << 1)
	connectionEventFieldCreatedAt = big.NewInt(1 << 2)
	connectionEventFieldID        = big.NewInt(1 << 3)
)

type ConnectionEvent struct {
	Action    string  `json:"action" url:"action"`
	Actor     string  `json:"actor" url:"actor"`
	CreatedAt float64 `json:"created_at" url:"created_at"`
	ID        string  `json:"id" url:"id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ConnectionEvent) GetAction() string {
	if c == nil {
		return ""
	}
	return c.Action
}

func (c *ConnectionEvent) GetActor() string {
	if c == nil {
		return ""
	}
	return c.Actor
}

func (c *ConnectionEvent) GetCreatedAt() float64 {
	if c == nil {
		return 0
	}
	return c.CreatedAt
}

func (c *ConnectionEvent) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *ConnectionEvent) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *ConnectionEvent) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAction sets the Action field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectionEvent) SetAction(action string) {
	c.Action = action
	c.require(connectionEventFieldAction)
}

// SetActor sets the Actor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectionEvent) SetActor(actor string) {
	c.Actor = actor
	c.require(connectionEventFieldActor)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectionEvent) SetCreatedAt(createdAt float64) {
	c.CreatedAt = createdAt
	c.require(connectionEventFieldCreatedAt)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectionEvent) SetID(id string) {
	c.ID = id
	c.require(connectionEventFieldID)
}

func (c *ConnectionEvent) UnmarshalJSON(data []byte) error {
	type unmarshaler ConnectionEvent
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ConnectionEvent(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ConnectionEvent) MarshalJSON() ([]byte, error) {
	type embed ConnectionEvent
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ConnectionEvent) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	connectionGrantFieldActive      = big.NewInt(1 << 0)
	connectionGrantFieldAgentID     = big.NewInt(1 << 1)
	connectionGrantFieldApproval    = big.NewInt(1 << 2)
	connectionGrantFieldEnvironment = big.NewInt(1 << 3)
	connectionGrantFieldID          = big.NewInt(1 << 4)
	connectionGrantFieldTools       = big.NewInt(1 << 5)
)

type ConnectionGrant struct {
	Active      bool              `json:"active" url:"active"`
	AgentID     string            `json:"agent_id" url:"agent_id"`
	Approval    string            `json:"approval" url:"approval"`
	Environment string            `json:"environment" url:"environment"`
	ID          string            `json:"id" url:"id"`
	Tools       map[string]string `json:"tools" url:"tools"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ConnectionGrant) GetActive() bool {
	if c == nil {
		return false
	}
	return c.Active
}

func (c *ConnectionGrant) GetAgentID() string {
	if c == nil {
		return ""
	}
	return c.AgentID
}

func (c *ConnectionGrant) GetApproval() string {
	if c == nil {
		return ""
	}
	return c.Approval
}

func (c *ConnectionGrant) GetEnvironment() string {
	if c == nil {
		return ""
	}
	return c.Environment
}

func (c *ConnectionGrant) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *ConnectionGrant) GetTools() map[string]string {
	if c == nil {
		return nil
	}
	return c.Tools
}

func (c *ConnectionGrant) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *ConnectionGrant) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetActive sets the Active field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectionGrant) SetActive(active bool) {
	c.Active = active
	c.require(connectionGrantFieldActive)
}

// SetAgentID sets the AgentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectionGrant) SetAgentID(agentID string) {
	c.AgentID = agentID
	c.require(connectionGrantFieldAgentID)
}

// SetApproval sets the Approval field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectionGrant) SetApproval(approval string) {
	c.Approval = approval
	c.require(connectionGrantFieldApproval)
}

// SetEnvironment sets the Environment field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectionGrant) SetEnvironment(environment string) {
	c.Environment = environment
	c.require(connectionGrantFieldEnvironment)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectionGrant) SetID(id string) {
	c.ID = id
	c.require(connectionGrantFieldID)
}

// SetTools sets the Tools field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectionGrant) SetTools(tools map[string]string) {
	c.Tools = tools
	c.require(connectionGrantFieldTools)
}

func (c *ConnectionGrant) UnmarshalJSON(data []byte) error {
	type unmarshaler ConnectionGrant
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ConnectionGrant(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ConnectionGrant) MarshalJSON() ([]byte, error) {
	type embed ConnectionGrant
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ConnectionGrant) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	connectionToolFieldDescription = big.NewInt(1 << 0)
	connectionToolFieldDigest      = big.NewInt(1 << 1)
	connectionToolFieldInputSchema = big.NewInt(1 << 2)
	connectionToolFieldName        = big.NewInt(1 << 3)
	connectionToolFieldVersion     = big.NewInt(1 << 4)
)

type ConnectionTool struct {
	Description *string        `json:"description,omitempty" url:"description,omitempty"`
	Digest      string         `json:"digest" url:"digest"`
	InputSchema map[string]any `json:"input_schema" url:"input_schema"`
	Name        string         `json:"name" url:"name"`
	Version     *string        `json:"version,omitempty" url:"version,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ConnectionTool) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *ConnectionTool) GetDigest() string {
	if c == nil {
		return ""
	}
	return c.Digest
}

func (c *ConnectionTool) GetInputSchema() map[string]any {
	if c == nil {
		return nil
	}
	return c.InputSchema
}

func (c *ConnectionTool) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *ConnectionTool) GetVersion() *string {
	if c == nil {
		return nil
	}
	return c.Version
}

func (c *ConnectionTool) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *ConnectionTool) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectionTool) SetDescription(description *string) {
	c.Description = description
	c.require(connectionToolFieldDescription)
}

// SetDigest sets the Digest field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectionTool) SetDigest(digest string) {
	c.Digest = digest
	c.require(connectionToolFieldDigest)
}

// SetInputSchema sets the InputSchema field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectionTool) SetInputSchema(inputSchema map[string]any) {
	c.InputSchema = inputSchema
	c.require(connectionToolFieldInputSchema)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectionTool) SetName(name string) {
	c.Name = name
	c.require(connectionToolFieldName)
}

// SetVersion sets the Version field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectionTool) SetVersion(version *string) {
	c.Version = version
	c.require(connectionToolFieldVersion)
}

func (c *ConnectionTool) UnmarshalJSON(data []byte) error {
	type unmarshaler ConnectionTool
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ConnectionTool(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ConnectionTool) MarshalJSON() ([]byte, error) {
	type embed ConnectionTool
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ConnectionTool) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CreateConnectionKind string

const (
	CreateConnectionKindMcp      CreateConnectionKind = "mcp"
	CreateConnectionKindComposio CreateConnectionKind = "composio"
)

func NewCreateConnectionKindFromString(s string) (CreateConnectionKind, error) {
	switch s {
	case "mcp":
		return CreateConnectionKindMcp, nil
	case "composio":
		return CreateConnectionKindComposio, nil
	}
	var t CreateConnectionKind
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateConnectionKind) Ptr() *CreateConnectionKind {
	return &c
}

type CreateConnectionOwnership string

const (
	CreateConnectionOwnershipWorkspace CreateConnectionOwnership = "workspace"
	CreateConnectionOwnershipPersonal  CreateConnectionOwnership = "personal"
)

func NewCreateConnectionOwnershipFromString(s string) (CreateConnectionOwnership, error) {
	switch s {
	case "workspace":
		return CreateConnectionOwnershipWorkspace, nil
	case "personal":
		return CreateConnectionOwnershipPersonal, nil
	}
	var t CreateConnectionOwnership
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateConnectionOwnership) Ptr() *CreateConnectionOwnership {
	return &c
}

type GrantConnectionApproval string

const (
	GrantConnectionApprovalAlways GrantConnectionApproval = "always"
	GrantConnectionApprovalNever  GrantConnectionApproval = "never"
)

func NewGrantConnectionApprovalFromString(s string) (GrantConnectionApproval, error) {
	switch s {
	case "always":
		return GrantConnectionApprovalAlways, nil
	case "never":
		return GrantConnectionApprovalNever, nil
	}
	var t GrantConnectionApproval
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GrantConnectionApproval) Ptr() *GrantConnectionApproval {
	return &g
}

type GrantConnectionEnvironment string

const (
	GrantConnectionEnvironmentDraft      GrantConnectionEnvironment = "draft"
	GrantConnectionEnvironmentStaging    GrantConnectionEnvironment = "staging"
	GrantConnectionEnvironmentProduction GrantConnectionEnvironment = "production"
)

func NewGrantConnectionEnvironmentFromString(s string) (GrantConnectionEnvironment, error) {
	switch s {
	case "draft":
		return GrantConnectionEnvironmentDraft, nil
	case "staging":
		return GrantConnectionEnvironmentStaging, nil
	case "production":
		return GrantConnectionEnvironmentProduction, nil
	}
	var t GrantConnectionEnvironment
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GrantConnectionEnvironment) Ptr() *GrantConnectionEnvironment {
	return &g
}
