# This file was auto-generated by Fern from our API Definition.

import typing

GetJudgeAlignmentJudgeAlignmentRequestEnvironment = typing.Union[
    typing.Literal["production", "staging", "development"], typing.Any
]
