# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.agent_budget import AgentBudget
from ..types.funding_receipt import FundingReceipt
from ..types.payment_setup_link import PaymentSetupLink
from .raw_client import AsyncRawAgentBudgetsClient, RawAgentBudgetsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AgentBudgetsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAgentBudgetsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAgentBudgetsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAgentBudgetsClient
        """
        return self._raw_client

    def get(
        self, project_id: str, harness_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AgentBudget:
        """
        Parameters
        ----------
        project_id : str

        harness_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentBudget
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            api_key="YOUR_API_KEY",
        )
        client.agent_budgets.get(
            project_id="project_id",
            harness_id="harness_id",
        )
        """
        _response = self._raw_client.get(project_id, harness_id, request_options=request_options)
        return _response.data

    def configure_auto_reload(
        self,
        project_id: str,
        harness_id: str,
        *,
        amount_usd: str,
        enabled: bool,
        threshold_usd: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AgentBudget:
        """
        Parameters
        ----------
        project_id : str

        harness_id : str

        amount_usd : str

        enabled : bool

        threshold_usd : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentBudget
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            api_key="YOUR_API_KEY",
        )
        client.agent_budgets.configure_auto_reload(
            project_id="project_id",
            harness_id="harness_id",
            amount_usd="amount_usd",
            enabled=True,
            threshold_usd="threshold_usd",
        )
        """
        _response = self._raw_client.configure_auto_reload(
            project_id,
            harness_id,
            amount_usd=amount_usd,
            enabled=enabled,
            threshold_usd=threshold_usd,
            request_options=request_options,
        )
        return _response.data

    def add(
        self,
        project_id: str,
        harness_id: str,
        *,
        amount_usd: str,
        idempotency_key: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FundingReceipt:
        """
        Parameters
        ----------
        project_id : str

        harness_id : str

        amount_usd : str

        idempotency_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FundingReceipt
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            api_key="YOUR_API_KEY",
        )
        client.agent_budgets.add(
            project_id="project_id",
            harness_id="harness_id",
            amount_usd="amount_usd",
            idempotency_key="idempotency_key",
        )
        """
        _response = self._raw_client.add(
            project_id,
            harness_id,
            amount_usd=amount_usd,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    def setup_payment_method(
        self,
        project_id: str,
        harness_id: str,
        *,
        idempotency_key: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaymentSetupLink:
        """
        Parameters
        ----------
        project_id : str

        harness_id : str

        idempotency_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaymentSetupLink
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            api_key="YOUR_API_KEY",
        )
        client.agent_budgets.setup_payment_method(
            project_id="project_id",
            harness_id="harness_id",
            idempotency_key="idempotency_key",
        )
        """
        _response = self._raw_client.setup_payment_method(
            project_id, harness_id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data


class AsyncAgentBudgetsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAgentBudgetsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAgentBudgetsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAgentBudgetsClient
        """
        return self._raw_client

    async def get(
        self, project_id: str, harness_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AgentBudget:
        """
        Parameters
        ----------
        project_id : str

        harness_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentBudget
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agent_budgets.get(
                project_id="project_id",
                harness_id="harness_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(project_id, harness_id, request_options=request_options)
        return _response.data

    async def configure_auto_reload(
        self,
        project_id: str,
        harness_id: str,
        *,
        amount_usd: str,
        enabled: bool,
        threshold_usd: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AgentBudget:
        """
        Parameters
        ----------
        project_id : str

        harness_id : str

        amount_usd : str

        enabled : bool

        threshold_usd : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentBudget
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agent_budgets.configure_auto_reload(
                project_id="project_id",
                harness_id="harness_id",
                amount_usd="amount_usd",
                enabled=True,
                threshold_usd="threshold_usd",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.configure_auto_reload(
            project_id,
            harness_id,
            amount_usd=amount_usd,
            enabled=enabled,
            threshold_usd=threshold_usd,
            request_options=request_options,
        )
        return _response.data

    async def add(
        self,
        project_id: str,
        harness_id: str,
        *,
        amount_usd: str,
        idempotency_key: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FundingReceipt:
        """
        Parameters
        ----------
        project_id : str

        harness_id : str

        amount_usd : str

        idempotency_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FundingReceipt
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agent_budgets.add(
                project_id="project_id",
                harness_id="harness_id",
                amount_usd="amount_usd",
                idempotency_key="idempotency_key",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.add(
            project_id,
            harness_id,
            amount_usd=amount_usd,
            idempotency_key=idempotency_key,
            request_options=request_options,
        )
        return _response.data

    async def setup_payment_method(
        self,
        project_id: str,
        harness_id: str,
        *,
        idempotency_key: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaymentSetupLink:
        """
        Parameters
        ----------
        project_id : str

        harness_id : str

        idempotency_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaymentSetupLink
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agent_budgets.setup_payment_method(
                project_id="project_id",
                harness_id="harness_id",
                idempotency_key="idempotency_key",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.setup_payment_method(
            project_id, harness_id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data
