# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .staged_definition_revision import StagedDefinitionRevision


class CreatedManagedAgent(UniversalBaseModel):
    """
    The created or existing agent. `definitionRevision` is present when a changed
    definition for an existing agent was staged as a draft revision.
    """

    definition_revision: typing_extensions.Annotated[
        typing.Optional[StagedDefinitionRevision],
        FieldMetadata(alias="definitionRevision"),
        pydantic.Field(alias="definitionRevision"),
    ] = None
    harness_version: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, typing.Any]],
        FieldMetadata(alias="harnessVersion"),
        pydantic.Field(alias="harnessVersion"),
    ] = None
    managed_agent: typing_extensions.Annotated[
        typing.Dict[str, typing.Any], FieldMetadata(alias="managedAgent"), pydantic.Field(alias="managedAgent")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
