# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .create_managed_agent_source_request_export_policy import CreateManagedAgentSourceRequestExportPolicy
from .create_managed_agent_source_request_source_kind import CreateManagedAgentSourceRequestSourceKind


class CreateManagedAgentSourceRequest(UniversalBaseModel):
    analysis_summary: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, typing.Any]],
        FieldMetadata(alias="analysisSummary"),
        pydantic.Field(alias="analysisSummary"),
    ] = None
    content_digest: typing_extensions.Annotated[
        str, FieldMetadata(alias="contentDigest"), pydantic.Field(alias="contentDigest")
    ]
    definition: typing.Optional[typing.Dict[str, typing.Any]] = None
    export_policy: typing_extensions.Annotated[
        typing.Optional[CreateManagedAgentSourceRequestExportPolicy],
        FieldMetadata(alias="exportPolicy"),
        pydantic.Field(alias="exportPolicy"),
    ] = None
    source_kind: typing_extensions.Annotated[
        typing.Optional[CreateManagedAgentSourceRequestSourceKind],
        FieldMetadata(alias="sourceKind"),
        pydantic.Field(alias="sourceKind"),
    ] = None
    storage_ref: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="storageRef"), pydantic.Field(alias="storageRef")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
