# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .document_editor_metadata import DocumentEditorMetadata
from .document_issue import DocumentIssue
from .resolved_mention import ResolvedMention


class DocumentValidationView(UniversalBaseModel):
    editor: typing.Optional[DocumentEditorMetadata] = None
    errors: typing.List[DocumentIssue]
    mentions: typing.List[ResolvedMention]
    publishable: bool

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
