# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class ExecutionTurnRun(UniversalBaseModel):
    harness_version_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="harnessVersionId"), pydantic.Field(alias="harnessVersionId")
    ]
    id: str
    input_id: typing_extensions.Annotated[str, FieldMetadata(alias="inputId"), pydantic.Field(alias="inputId")]
    session_id: typing_extensions.Annotated[str, FieldMetadata(alias="sessionId"), pydantic.Field(alias="sessionId")]
    status: str
    trace_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="traceId"), pydantic.Field(alias="traceId")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
