# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .http_output import HttpOutput
from .http_receipt_status import HttpReceiptStatus


class HttpReceipt(UniversalBaseModel):
    id: str
    operator_url: typing.Optional[str] = None
    output: typing.Optional[HttpOutput] = None
    run_id: typing.Optional[str] = None
    session_id: typing.Optional[str] = None
    status: HttpReceiptStatus
    status_url: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
