# This file was auto-generated by Fern from our API Definition.

import typing

OperationViewMethod = typing.Union[
    typing.Literal["bash.start", "bash.read", "bash.wait", "bash.cancel", "workspace.write_text"], typing.Any
]
