# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .mention import Mention


class ResolvedMention(UniversalBaseModel):
    allowed_hosts: typing.Optional[typing.List[str]] = None
    mention: Mention
    reason: typing.Optional[str] = None
    resource_id: typing.Optional[str] = None
    state: str
    tool_digests: typing.Optional[typing.Dict[str, str]] = None
    warning: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
