# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from .run_transcript_evidence import RunTranscriptEvidence
from .transcript_event import TranscriptEvent
from .transcript_run import TranscriptRun


class RunTranscript(UniversalBaseModel):
    events: typing.List[TranscriptEvent]
    evidence: RunTranscriptEvidence
    run: TranscriptRun
    trajectory: typing.Optional["TranscriptTrajectory"] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .transcript_trajectory import TranscriptTrajectory  # noqa: E402, I001

update_forward_refs(RunTranscript, TranscriptTrajectory=TranscriptTrajectory)
