# This file was auto-generated by Fern from our API Definition.

import typing

WorkPageExecutionPhase = typing.Union[
    typing.Literal["idle", "running", "waiting_approval", "checkpointing", "terminal"], typing.Any
]
