// This file was auto-generated by Fern from our API Definition.

import * as Sikaru from "../index.js";

export interface AgentWebCapabilities {
    allow_domains?: string[] | undefined;
    block_domains?: string[] | undefined;
    provider?: AgentWebCapabilities.Provider | undefined;
}

export namespace AgentWebCapabilities {
    export type Provider = 
        | ("sikaru")
        | Sikaru.ConnectionToolRef;
}
