// This file was auto-generated by Fern from our API Definition.

import * as Sikaru from "../index.js";

export interface AgentDocumentDraft {
    checks: Sikaru.StarterCheck[];
    document: string;
    name: string;
    notes: string[];
    /** Toolkit slugs the agent expects, connected or not. */
    tools: string[];
}
