// This file was auto-generated by Fern from our API Definition.

/**
 * Per-project ceilings. The defaults impose no limit.
 */
export interface CapabilityCeilings {
    allowedGitHosts?: (string[] | null) | undefined;
    disallowedTools?: CapabilityCeilings.DisallowedTools.Item[] | undefined;
    domainDenylist?: string[] | undefined;
    egressEnabled?: boolean | undefined;
}

export namespace CapabilityCeilings {
    export type DisallowedTools = DisallowedTools.Item[];

    export namespace DisallowedTools {
        export const Item = {
                Bash: "bash",
                Workspace: "workspace",
                Agents: "agents",
                Memory: "memory",
                WebSearch: "web_search",
                WebFetch: "web_fetch"
            } as const;
        export type Item = typeof Item[keyof typeof Item];
    }
}
