// This file was auto-generated by Fern from our API Definition.

export interface ChannelIdentityApp {
    audience: string;
    connection_callback_url?: (string | null) | undefined;
    id: string;
    issuer: string;
    private_channel_url?: (string | null) | undefined;
    status: string;
}
