// This file was auto-generated by Fern from our API Definition.

export interface ConnectionCredentials {
    oauth_client_secret?: (string | null) | undefined;
    token?: (string | null) | undefined;
}
