// This file was auto-generated by Fern from our API Definition.

export interface ConnectionTool {
    description?: string | undefined;
    digest: string;
    input_schema: Record<string, unknown>;
    name: string;
    version?: (string | null) | undefined;
}
