// This file was auto-generated by Fern from our API Definition.

import * as Sikaru from "../index.js";

export interface DatasetChecksStarted {
    agentVersion: string;
    checks: Sikaru.StartedCheck[];
    datasetVersion: number;
    notEligible: Record<string, number>;
}
