// This file was auto-generated by Fern from our API Definition.

import * as Sikaru from "../index.js";

export interface DefinitionRevision {
    baseHarnessVersionId: string;
    candidateHarnessVersionId: string;
    changes: Sikaru.DefinitionChange[];
    changeset: Record<string, unknown>;
    definitionDigest: string;
}
