// This file was auto-generated by Fern from our API Definition.

import * as Sikaru from "../index.js";

export interface DocumentComparison {
    diff: string;
    draft: Sikaru.DocumentRevision;
    liveDocument: string;
    liveVersionId: string | null;
}
