// This file was auto-generated by Fern from our API Definition.

export interface Mention {
    column: number;
    end: number;
    kind: string;
    line: number;
    slug: string;
    start: number;
    text: string;
}
