// This file was auto-generated by Fern from our API Definition.

export interface ResourceBudget {
    /** Spending cap in USD; null means uncapped complimentary usage */
    limit_usd: string | null;
    reserved_usd: string;
    used_usd: string;
}
