// This file was auto-generated by Fern from our API Definition.

export interface WorkspaceCheckpointView {
    checkpoint_id: string;
    owner_epoch: number;
    run_id: string;
    status: WorkspaceCheckpointView.Status;
    tree_id?: (string | null) | undefined;
    workspace_generation: string;
}

export namespace WorkspaceCheckpointView {
    export const Status = {
            Requested: "requested",
            Unsupported: "unsupported",
            Publishing: "publishing",
            Published: "published"
        } as const;
    export type Status = typeof Status[keyof typeof Status];
}
