// This file was auto-generated by Fern from our API Definition.

export interface WorkspaceRemoteView {
    branch: string;
    expires_at: string;
    head_sha: string | null;
    ignore_defaults: string[];
    max_push_bytes: number;
    remote_url: string;
    /** Short-lived push credential for this session branch. Treat it as a secret. */
    token: string;
    username: WorkspaceRemoteView.Username;
}

export namespace WorkspaceRemoteView {
    export const Username = {
            XToken: "x-token"
        } as const;
    export type Username = typeof Username[keyof typeof Username];
}
