// This file was auto-generated by Fern from our API Definition.

import * as Sikaru from "../../../../index.js";

/**
 * @example
 *     {
 *         environment_id: "environment_id",
 *         idempotency_key: "idempotency_key",
 *         workspace_provenance: {
 *             identity: "identity",
 *             kind: "existing_directory"
 *         }
 *     }
 */
export interface AttachmentInput {
    environment_id: string;
    idempotency_key: string;
    replace_existing?: boolean;
    workspace_provenance: Sikaru.WorkspaceProvenance;
}
