# This file was auto-generated by Fern from our API Definition.

import typing

CreateTraceImportRequestProvider = typing.Union[
    typing.Literal["langsmith", "langfuse", "braintrust", "logfire", "harbor", "opentelemetry", "openinference"],
    typing.Any,
]
