# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.approval_input_decision import ApprovalInputDecision
from ..types.connection_authorization import ConnectionAuthorization
from ..types.connection_credentials import ConnectionCredentials
from ..types.personal_channel_approval import PersonalChannelApproval
from ..types.personal_channel_connection import PersonalChannelConnection
from ..types.personal_channel_files import PersonalChannelFiles
from ..types.personal_channel_receipt import PersonalChannelReceipt
from ..types.personal_slack_challenge import PersonalSlackChallenge
from ..types.personal_slack_status import PersonalSlackStatus
from .raw_client import AsyncRawPersonalChannelsClient, RawPersonalChannelsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class PersonalChannelsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPersonalChannelsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPersonalChannelsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPersonalChannelsClient
        """
        return self._raw_client

    def get_message(
        self,
        binding_id: str,
        receipt_id: str,
        *,
        authorization: typing.Optional[str] = None,
        sikaru_user_assertion: typing.Optional[str] = None,
        sikaru_member_authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PersonalChannelReceipt:
        """
        Parameters
        ----------
        binding_id : str

        receipt_id : str

        authorization : typing.Optional[str]

        sikaru_user_assertion : typing.Optional[str]

        sikaru_member_authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PersonalChannelReceipt
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.personal_channels.get_message(
            binding_id="binding_id",
            receipt_id="receipt_id",
        )
        """
        _response = self._raw_client.get_message(
            binding_id,
            receipt_id,
            authorization=authorization,
            sikaru_user_assertion=sikaru_user_assertion,
            sikaru_member_authorization=sikaru_member_authorization,
            request_options=request_options,
        )
        return _response.data

    def authorize_connection(
        self,
        binding_id: str,
        receipt_id: str,
        connection_id: str,
        *,
        authorization: typing.Optional[str] = None,
        sikaru_user_assertion: typing.Optional[str] = None,
        sikaru_member_authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ConnectionAuthorization:
        """
        Parameters
        ----------
        binding_id : str

        receipt_id : str

        connection_id : str

        authorization : typing.Optional[str]

        sikaru_user_assertion : typing.Optional[str]

        sikaru_member_authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConnectionAuthorization
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.personal_channels.authorize_connection(
            binding_id="binding_id",
            receipt_id="receipt_id",
            connection_id="connection_id",
        )
        """
        _response = self._raw_client.authorize_connection(
            binding_id,
            receipt_id,
            connection_id,
            authorization=authorization,
            sikaru_user_assertion=sikaru_user_assertion,
            sikaru_member_authorization=sikaru_member_authorization,
            request_options=request_options,
        )
        return _response.data

    def complete_connection(
        self,
        binding_id: str,
        receipt_id: str,
        connection_id: str,
        *,
        state: str,
        authorization: typing.Optional[str] = None,
        sikaru_user_assertion: typing.Optional[str] = None,
        sikaru_member_authorization: typing.Optional[str] = None,
        query: typing.Optional[typing.Dict[str, str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PersonalChannelConnection:
        """
        Parameters
        ----------
        binding_id : str

        receipt_id : str

        connection_id : str

        state : str

        authorization : typing.Optional[str]

        sikaru_user_assertion : typing.Optional[str]

        sikaru_member_authorization : typing.Optional[str]

        query : typing.Optional[typing.Dict[str, str]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PersonalChannelConnection
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.personal_channels.complete_connection(
            binding_id="binding_id",
            receipt_id="receipt_id",
            connection_id="connection_id",
            state="state",
        )
        """
        _response = self._raw_client.complete_connection(
            binding_id,
            receipt_id,
            connection_id,
            state=state,
            authorization=authorization,
            sikaru_user_assertion=sikaru_user_assertion,
            sikaru_member_authorization=sikaru_member_authorization,
            query=query,
            request_options=request_options,
        )
        return _response.data

    def replace_connection_credentials(
        self,
        binding_id: str,
        receipt_id: str,
        connection_id: str,
        *,
        credentials: ConnectionCredentials,
        authorization: typing.Optional[str] = None,
        sikaru_user_assertion: typing.Optional[str] = None,
        sikaru_member_authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PersonalChannelConnection:
        """
        Parameters
        ----------
        binding_id : str

        receipt_id : str

        connection_id : str

        credentials : ConnectionCredentials

        authorization : typing.Optional[str]

        sikaru_user_assertion : typing.Optional[str]

        sikaru_member_authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PersonalChannelConnection
            Successful Response

        Examples
        --------
        from sikaru_api import ConnectionCredentials, SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.personal_channels.replace_connection_credentials(
            binding_id="binding_id",
            receipt_id="receipt_id",
            connection_id="connection_id",
            credentials=ConnectionCredentials(),
        )
        """
        _response = self._raw_client.replace_connection_credentials(
            binding_id,
            receipt_id,
            connection_id,
            credentials=credentials,
            authorization=authorization,
            sikaru_user_assertion=sikaru_user_assertion,
            sikaru_member_authorization=sikaru_member_authorization,
            request_options=request_options,
        )
        return _response.data

    def list_files(
        self,
        binding_id: str,
        receipt_id: str,
        *,
        authorization: typing.Optional[str] = None,
        sikaru_user_assertion: typing.Optional[str] = None,
        sikaru_member_authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PersonalChannelFiles:
        """
        Parameters
        ----------
        binding_id : str

        receipt_id : str

        authorization : typing.Optional[str]

        sikaru_user_assertion : typing.Optional[str]

        sikaru_member_authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PersonalChannelFiles
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.personal_channels.list_files(
            binding_id="binding_id",
            receipt_id="receipt_id",
        )
        """
        _response = self._raw_client.list_files(
            binding_id,
            receipt_id,
            authorization=authorization,
            sikaru_user_assertion=sikaru_user_assertion,
            sikaru_member_authorization=sikaru_member_authorization,
            request_options=request_options,
        )
        return _response.data

    def download_file(
        self,
        binding_id: str,
        receipt_id: str,
        file_id: str,
        *,
        authorization: typing.Optional[str] = None,
        sikaru_user_assertion: typing.Optional[str] = None,
        sikaru_member_authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Iterator[bytes]:
        """
        Parameters
        ----------
        binding_id : str

        receipt_id : str

        file_id : str

        authorization : typing.Optional[str]

        sikaru_user_assertion : typing.Optional[str]

        sikaru_member_authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.Iterator[bytes]
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.personal_channels.download_file(
            binding_id="binding_id",
            receipt_id="receipt_id",
            file_id="file_id",
        )
        """
        with self._raw_client.download_file(
            binding_id,
            receipt_id,
            file_id,
            authorization=authorization,
            sikaru_user_assertion=sikaru_user_assertion,
            sikaru_member_authorization=sikaru_member_authorization,
            request_options=request_options,
        ) as r:
            yield from r.data

    def decide_approval(
        self,
        binding_id: str,
        receipt_id: str,
        tool_call_id: str,
        *,
        decision: ApprovalInputDecision,
        idempotency_key: str,
        authorization: typing.Optional[str] = None,
        sikaru_user_assertion: typing.Optional[str] = None,
        sikaru_member_authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PersonalChannelApproval:
        """
        Parameters
        ----------
        binding_id : str

        receipt_id : str

        tool_call_id : str

        decision : ApprovalInputDecision

        idempotency_key : str

        authorization : typing.Optional[str]

        sikaru_user_assertion : typing.Optional[str]

        sikaru_member_authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PersonalChannelApproval
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.personal_channels.decide_approval(
            binding_id="binding_id",
            receipt_id="receipt_id",
            tool_call_id="tool_call_id",
            decision="approved",
            idempotency_key="idempotency_key",
        )
        """
        _response = self._raw_client.decide_approval(
            binding_id,
            receipt_id,
            tool_call_id,
            decision=decision,
            idempotency_key=idempotency_key,
            authorization=authorization,
            sikaru_user_assertion=sikaru_user_assertion,
            sikaru_member_authorization=sikaru_member_authorization,
            request_options=request_options,
        )
        return _response.data

    def get_slack_link(
        self,
        binding_id: str,
        verification_id: str,
        *,
        authorization: typing.Optional[str] = None,
        sikaru_user_assertion: typing.Optional[str] = None,
        sikaru_member_authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PersonalSlackStatus:
        """
        Parameters
        ----------
        binding_id : str

        verification_id : str

        authorization : typing.Optional[str]

        sikaru_user_assertion : typing.Optional[str]

        sikaru_member_authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PersonalSlackStatus
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.personal_channels.get_slack_link(
            binding_id="binding_id",
            verification_id="verification_id",
        )
        """
        _response = self._raw_client.get_slack_link(
            binding_id,
            verification_id,
            authorization=authorization,
            sikaru_user_assertion=sikaru_user_assertion,
            sikaru_member_authorization=sikaru_member_authorization,
            request_options=request_options,
        )
        return _response.data

    def start_slack_link(
        self,
        binding_id: str,
        *,
        installation_id: str,
        authorization: typing.Optional[str] = None,
        sikaru_user_assertion: typing.Optional[str] = None,
        sikaru_member_authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PersonalSlackChallenge:
        """
        Parameters
        ----------
        binding_id : str

        installation_id : str

        authorization : typing.Optional[str]

        sikaru_user_assertion : typing.Optional[str]

        sikaru_member_authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PersonalSlackChallenge
            Successful Response

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.personal_channels.start_slack_link(
            binding_id="binding_id",
            installation_id="installation_id",
        )
        """
        _response = self._raw_client.start_slack_link(
            binding_id,
            installation_id=installation_id,
            authorization=authorization,
            sikaru_user_assertion=sikaru_user_assertion,
            sikaru_member_authorization=sikaru_member_authorization,
            request_options=request_options,
        )
        return _response.data

    def unlink_slack_identity(
        self,
        binding_id: str,
        installation_id: str,
        *,
        authorization: typing.Optional[str] = None,
        sikaru_user_assertion: typing.Optional[str] = None,
        sikaru_member_authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Parameters
        ----------
        binding_id : str

        installation_id : str

        authorization : typing.Optional[str]

        sikaru_user_assertion : typing.Optional[str]

        sikaru_member_authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from sikaru_api import SikaruApi

        client = SikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )
        client.personal_channels.unlink_slack_identity(
            binding_id="binding_id",
            installation_id="installation_id",
        )
        """
        _response = self._raw_client.unlink_slack_identity(
            binding_id,
            installation_id,
            authorization=authorization,
            sikaru_user_assertion=sikaru_user_assertion,
            sikaru_member_authorization=sikaru_member_authorization,
            request_options=request_options,
        )
        return _response.data


class AsyncPersonalChannelsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPersonalChannelsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPersonalChannelsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPersonalChannelsClient
        """
        return self._raw_client

    async def get_message(
        self,
        binding_id: str,
        receipt_id: str,
        *,
        authorization: typing.Optional[str] = None,
        sikaru_user_assertion: typing.Optional[str] = None,
        sikaru_member_authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PersonalChannelReceipt:
        """
        Parameters
        ----------
        binding_id : str

        receipt_id : str

        authorization : typing.Optional[str]

        sikaru_user_assertion : typing.Optional[str]

        sikaru_member_authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PersonalChannelReceipt
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.personal_channels.get_message(
                binding_id="binding_id",
                receipt_id="receipt_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_message(
            binding_id,
            receipt_id,
            authorization=authorization,
            sikaru_user_assertion=sikaru_user_assertion,
            sikaru_member_authorization=sikaru_member_authorization,
            request_options=request_options,
        )
        return _response.data

    async def authorize_connection(
        self,
        binding_id: str,
        receipt_id: str,
        connection_id: str,
        *,
        authorization: typing.Optional[str] = None,
        sikaru_user_assertion: typing.Optional[str] = None,
        sikaru_member_authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ConnectionAuthorization:
        """
        Parameters
        ----------
        binding_id : str

        receipt_id : str

        connection_id : str

        authorization : typing.Optional[str]

        sikaru_user_assertion : typing.Optional[str]

        sikaru_member_authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConnectionAuthorization
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.personal_channels.authorize_connection(
                binding_id="binding_id",
                receipt_id="receipt_id",
                connection_id="connection_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.authorize_connection(
            binding_id,
            receipt_id,
            connection_id,
            authorization=authorization,
            sikaru_user_assertion=sikaru_user_assertion,
            sikaru_member_authorization=sikaru_member_authorization,
            request_options=request_options,
        )
        return _response.data

    async def complete_connection(
        self,
        binding_id: str,
        receipt_id: str,
        connection_id: str,
        *,
        state: str,
        authorization: typing.Optional[str] = None,
        sikaru_user_assertion: typing.Optional[str] = None,
        sikaru_member_authorization: typing.Optional[str] = None,
        query: typing.Optional[typing.Dict[str, str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PersonalChannelConnection:
        """
        Parameters
        ----------
        binding_id : str

        receipt_id : str

        connection_id : str

        state : str

        authorization : typing.Optional[str]

        sikaru_user_assertion : typing.Optional[str]

        sikaru_member_authorization : typing.Optional[str]

        query : typing.Optional[typing.Dict[str, str]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PersonalChannelConnection
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.personal_channels.complete_connection(
                binding_id="binding_id",
                receipt_id="receipt_id",
                connection_id="connection_id",
                state="state",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.complete_connection(
            binding_id,
            receipt_id,
            connection_id,
            state=state,
            authorization=authorization,
            sikaru_user_assertion=sikaru_user_assertion,
            sikaru_member_authorization=sikaru_member_authorization,
            query=query,
            request_options=request_options,
        )
        return _response.data

    async def replace_connection_credentials(
        self,
        binding_id: str,
        receipt_id: str,
        connection_id: str,
        *,
        credentials: ConnectionCredentials,
        authorization: typing.Optional[str] = None,
        sikaru_user_assertion: typing.Optional[str] = None,
        sikaru_member_authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PersonalChannelConnection:
        """
        Parameters
        ----------
        binding_id : str

        receipt_id : str

        connection_id : str

        credentials : ConnectionCredentials

        authorization : typing.Optional[str]

        sikaru_user_assertion : typing.Optional[str]

        sikaru_member_authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PersonalChannelConnection
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi, ConnectionCredentials

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.personal_channels.replace_connection_credentials(
                binding_id="binding_id",
                receipt_id="receipt_id",
                connection_id="connection_id",
                credentials=ConnectionCredentials(),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.replace_connection_credentials(
            binding_id,
            receipt_id,
            connection_id,
            credentials=credentials,
            authorization=authorization,
            sikaru_user_assertion=sikaru_user_assertion,
            sikaru_member_authorization=sikaru_member_authorization,
            request_options=request_options,
        )
        return _response.data

    async def list_files(
        self,
        binding_id: str,
        receipt_id: str,
        *,
        authorization: typing.Optional[str] = None,
        sikaru_user_assertion: typing.Optional[str] = None,
        sikaru_member_authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PersonalChannelFiles:
        """
        Parameters
        ----------
        binding_id : str

        receipt_id : str

        authorization : typing.Optional[str]

        sikaru_user_assertion : typing.Optional[str]

        sikaru_member_authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PersonalChannelFiles
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.personal_channels.list_files(
                binding_id="binding_id",
                receipt_id="receipt_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_files(
            binding_id,
            receipt_id,
            authorization=authorization,
            sikaru_user_assertion=sikaru_user_assertion,
            sikaru_member_authorization=sikaru_member_authorization,
            request_options=request_options,
        )
        return _response.data

    async def download_file(
        self,
        binding_id: str,
        receipt_id: str,
        file_id: str,
        *,
        authorization: typing.Optional[str] = None,
        sikaru_user_assertion: typing.Optional[str] = None,
        sikaru_member_authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.AsyncIterator[bytes]:
        """
        Parameters
        ----------
        binding_id : str

        receipt_id : str

        file_id : str

        authorization : typing.Optional[str]

        sikaru_user_assertion : typing.Optional[str]

        sikaru_member_authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.AsyncIterator[bytes]
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.personal_channels.download_file(
                binding_id="binding_id",
                receipt_id="receipt_id",
                file_id="file_id",
            )


        asyncio.run(main())
        """
        async with self._raw_client.download_file(
            binding_id,
            receipt_id,
            file_id,
            authorization=authorization,
            sikaru_user_assertion=sikaru_user_assertion,
            sikaru_member_authorization=sikaru_member_authorization,
            request_options=request_options,
        ) as r:
            async for _chunk in r.data:
                yield _chunk

    async def decide_approval(
        self,
        binding_id: str,
        receipt_id: str,
        tool_call_id: str,
        *,
        decision: ApprovalInputDecision,
        idempotency_key: str,
        authorization: typing.Optional[str] = None,
        sikaru_user_assertion: typing.Optional[str] = None,
        sikaru_member_authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PersonalChannelApproval:
        """
        Parameters
        ----------
        binding_id : str

        receipt_id : str

        tool_call_id : str

        decision : ApprovalInputDecision

        idempotency_key : str

        authorization : typing.Optional[str]

        sikaru_user_assertion : typing.Optional[str]

        sikaru_member_authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PersonalChannelApproval
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.personal_channels.decide_approval(
                binding_id="binding_id",
                receipt_id="receipt_id",
                tool_call_id="tool_call_id",
                decision="approved",
                idempotency_key="idempotency_key",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.decide_approval(
            binding_id,
            receipt_id,
            tool_call_id,
            decision=decision,
            idempotency_key=idempotency_key,
            authorization=authorization,
            sikaru_user_assertion=sikaru_user_assertion,
            sikaru_member_authorization=sikaru_member_authorization,
            request_options=request_options,
        )
        return _response.data

    async def get_slack_link(
        self,
        binding_id: str,
        verification_id: str,
        *,
        authorization: typing.Optional[str] = None,
        sikaru_user_assertion: typing.Optional[str] = None,
        sikaru_member_authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PersonalSlackStatus:
        """
        Parameters
        ----------
        binding_id : str

        verification_id : str

        authorization : typing.Optional[str]

        sikaru_user_assertion : typing.Optional[str]

        sikaru_member_authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PersonalSlackStatus
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.personal_channels.get_slack_link(
                binding_id="binding_id",
                verification_id="verification_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_slack_link(
            binding_id,
            verification_id,
            authorization=authorization,
            sikaru_user_assertion=sikaru_user_assertion,
            sikaru_member_authorization=sikaru_member_authorization,
            request_options=request_options,
        )
        return _response.data

    async def start_slack_link(
        self,
        binding_id: str,
        *,
        installation_id: str,
        authorization: typing.Optional[str] = None,
        sikaru_user_assertion: typing.Optional[str] = None,
        sikaru_member_authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PersonalSlackChallenge:
        """
        Parameters
        ----------
        binding_id : str

        installation_id : str

        authorization : typing.Optional[str]

        sikaru_user_assertion : typing.Optional[str]

        sikaru_member_authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PersonalSlackChallenge
            Successful Response

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.personal_channels.start_slack_link(
                binding_id="binding_id",
                installation_id="installation_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.start_slack_link(
            binding_id,
            installation_id=installation_id,
            authorization=authorization,
            sikaru_user_assertion=sikaru_user_assertion,
            sikaru_member_authorization=sikaru_member_authorization,
            request_options=request_options,
        )
        return _response.data

    async def unlink_slack_identity(
        self,
        binding_id: str,
        installation_id: str,
        *,
        authorization: typing.Optional[str] = None,
        sikaru_user_assertion: typing.Optional[str] = None,
        sikaru_member_authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Parameters
        ----------
        binding_id : str

        installation_id : str

        authorization : typing.Optional[str]

        sikaru_user_assertion : typing.Optional[str]

        sikaru_member_authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from sikaru_api import AsyncSikaruApi

        client = AsyncSikaruApi(
            channel_credential="YOUR_CHANNEL_CREDENTIAL",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.personal_channels.unlink_slack_identity(
                binding_id="binding_id",
                installation_id="installation_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.unlink_slack_identity(
            binding_id,
            installation_id,
            authorization=authorization,
            sikaru_user_assertion=sikaru_user_assertion,
            sikaru_member_authorization=sikaru_member_authorization,
            request_options=request_options,
        )
        return _response.data
